import { ASSESS_STEPS, DATE, EAU_PRP, NO_GUARANTEE } from "../shared";
import type { PageDef } from "../types";

const TRUST = { name: "About", path: "/about" };

export const clinicPages: PageDef[] = [
  {
    path: "/penile-rehabilitation",
    metaTitle: "Penile Rehabilitation Programme | UZ Clinic Antalya",
    description:
      "Penile rehabilitation is a structured, cause-based plan to support erectile function, for example after prostate surgery. How it works and who it may suit.",
    h1: "Penile Rehabilitation Programme",
    eyebrow: "Treatment programme",
    kind: "money",
    treatment: "rehabilitation",
    medical: true,
    evidence: "Individualised",
    answer: {
      q: "What is penile rehabilitation?",
      a: "Penile rehabilitation is a structured plan to support erectile function and penile tissue health, most often after prostate surgery or other pelvic procedures, but also for men who want a planned approach to ED. It may combine medication, devices and other therapies, chosen after assessment. Outcomes vary, and no result can be guaranteed.",
    },
    ctaLabel: "Ask About Penile Rehabilitation",
    modified: DATE,
    priority: 0.8,
    schema: { therapy: "Penile rehabilitation", condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "cards",
        heading: "Who may benefit from a rehabilitation plan",
        id: "who",
        cols: 2,
        cards: [
          { title: "After prostate surgery", text: "Men recovering after radical prostatectomy, where nerves and blood vessels may be affected.", href: "/erectile-dysfunction-after-prostate-surgery" },
          { title: "After pelvic surgery or injury", text: "Men with ED following other pelvic procedures or trauma." },
          { title: "Long-standing ED", text: "Men who have had ED for some time and want a structured, cause-based plan." },
          { title: "Blood-flow related ED", text: "Men whose assessment points to a vascular pattern.", href: "/vasculogenic-erectile-dysfunction" },
        ],
      },
      {
        type: "text",
        heading: "What a plan may include",
        id: "components",
        bullets: [
          "Treatment of underlying risk factors such as diabetes, blood pressure and cholesterol.",
          "Medication, such as PDE5 tablets, where appropriate.",
          "Vacuum devices or injections in some men.",
          "Shockwave therapy in selected men with a blood-flow pattern.",
          "Experimental options only after assessment, informed consent and discussion of alternatives.",
          "Follow-up to review progress and adjust the plan.",
        ],
        note: "The actual components are decided by the doctor after your assessment.",
      },
      { type: "cta", title: "Plan Your Rehabilitation With a Urologist", text: "Send your history, and surgery details if relevant. The clinic can advise on next steps.", label: "Ask About Penile Rehabilitation" },
      { type: "steps", heading: "How the process works", id: "process", steps: ASSESS_STEPS },
      { type: "treatment-nav", heading: "Treatments that may form part of a plan", exclude: ["rehabilitation"] },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Is penile rehabilitation guaranteed to restore erections?", a: NO_GUARANTEE },
      { q: "When should rehabilitation start after surgery?", a: "Timing is individualised. Ask your surgeon or the clinic's urologist." },
      { q: "Does rehabilitation involve regenerative therapies?", a: "Only when they are appropriate and you have given informed consent. " + EAU_PRP },
    ],
    sources: ["eau2026", "aua2018"],
    related: ["/erectile-dysfunction-after-prostate-surgery", "/penile-implant", "/ed-treatment-options", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/penile-implant",
    metaTitle: "Penile Implant for ED: When Is It Considered?",
    description:
      "A penile implant is an established surgical option for severe ED that has not responded to other treatments. How it works and what to ask a surgeon.",
    h1: "Penile Implant for Erectile Dysfunction",
    eyebrow: "Surgical option",
    kind: "money",
    treatment: "rehabilitation",
    medical: true,
    evidence: "Established",
    answer: {
      q: "When is a penile implant considered for ED?",
      a: "A penile implant is an established surgical treatment for severe ED, usually considered when other options have not worked or are unsuitable. A device is placed in the penis to allow an erection on demand. It needs surgical assessment, and the doctor explains the benefits, risks and alternatives.",
    },
    ctaLabel: "Ask the Urologist About Implants",
    modified: DATE,
    priority: 0.6,
    blocks: [
      {
        type: "text",
        heading: "How an implant works",
        id: "how",
        paragraphs: [
          "Implants are inflatable or malleable devices placed during an operation. They do not change sensation or desire, but allow an erection to be created when wanted.",
        ],
      },
      {
        type: "text",
        heading: "Who may be considered",
        id: "who",
        bullets: [
          "Men with severe ED who have not responded to, or cannot use, tablets, injections or devices.",
          "Men with ED after surgery, injury or disease where other options are limited.",
        ],
        note: "It is a decision to be made with a surgeon, after realistic discussion of benefits, risks and alternatives. Please ask the clinic whether implant surgery is part of the plan for your case.",
      },
      { type: "cta", title: "Ask the Urologist About Surgical Options", text: "Tell us what you have tried. The clinic can advise on what is relevant.", label: "Ask the Urologist About Implants", whatsapp: true },
      { type: "comparison", highlight: ["implant", "pde5", "injections"] },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Is a penile implant permanent?", a: "It is a long-term device, but it can wear out or need revision. The surgeon explains this." },
      { q: "What are the risks?", a: "Surgical risks include infection, mechanical problems and the need for further surgery. The surgeon discusses them in detail." },
    ],
    sources: ["eau2026", "aua2018"],
    related: ["/penile-rehabilitation", "/ed-treatment-options", "/erectile-dysfunction-after-prostate-surgery", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/dr-niyazi-umut-ozdemir",
    metaTitle: "Dr. Niyazi Umut Özdemir | Urological Surgeon, Antalya",
    description:
      "Dr. Niyazi Umut Özdemir is a urological surgeon in Antalya focused on male sexual health and penile rehabilitation. Qualifications and clinical focus.",
    h1: "Dr. Niyazi Umut Özdemir, Urological Surgeon",
    eyebrow: "Your physician",
    kind: "trust",
    medical: false,
    parent: TRUST,
    answer: {
      q: "Who is Dr. Niyazi Umut Özdemir?",
      a: "Dr. Niyazi Umut Özdemir is a urological surgeon in Antalya, Turkey, and the physician responsible for UZ Clinic Antalya. He studied medicine at Ege University, specialised in urology and holds Turkish Association of Urology board certification. His clinical focus is male sexual health and penile rehabilitation.",
    },
    ctaLabel: "Ask the Urologist",
    modified: DATE,
    priority: 0.7,
    blocks: [
      { type: "doctor" },
      {
        type: "text",
        heading: "How the clinic works",
        id: "approach",
        bullets: [
          "Assessment before treatment, so the plan follows the cause of ED.",
          "Established, emerging and experimental treatments are labelled honestly.",
          "Written informed consent, including evidence, risks and alternatives.",
          "Confidential communication, with a patient coordinator for international patients.",
        ],
      },
      { type: "cta", title: "Ask the Urologist", text: "Send your case. The clinic will tell you which options may be relevant.", label: "Ask the Urologist", whatsapp: true },
    ],
    related: ["/about", "/erectile-dysfunction-assessment", "/ed-treatment-options", "/international-patients"],
  },
  {
    path: "/about",
    metaTitle: "About UZ Clinic Antalya | Male Sexual Health Urology",
    description:
      "UZ Clinic Antalya is a urologist-led service for erectile dysfunction and penile rehabilitation. Who we are, how we work and how we handle evidence.",
    h1: "About UZ Clinic Antalya",
    eyebrow: "The clinic",
    kind: "trust",
    medical: false,
    answer: {
      q: "What is UZ Clinic Antalya?",
      a: "UZ Clinic Antalya is a physician-led urology and penile rehabilitation service in Antalya, Turkey, focused on male sexual health. The clinic is led by Dr. Niyazi Umut Özdemir, a urological surgeon. It is not a beauty clinic or a medical-tourism agency. Patients are assessed by a doctor, and treatment is planned around the cause of ED.",
    },
    ctaLabel: "Request a Confidential ED Assessment",
    modified: DATE,
    priority: 0.6,
    blocks: [
      {
        type: "cards",
        heading: "What we treat",
        id: "treat",
        cols: 2,
        cards: [
          { title: "Erectile dysfunction", text: "Cause-based assessment and treatment planning.", href: "/erectile-dysfunction" },
          { title: "Vasculogenic ED and venous leak", text: "Blood-flow assessment and options.", href: "/vasculogenic-erectile-dysfunction" },
          { title: "Penile rehabilitation", text: "Structured plans, for example after prostate surgery.", href: "/penile-rehabilitation" },
          { title: "Shockwave, PRP and regenerative options", text: "Offered after assessment, with honest evidence information.", href: "/ed-treatment-options" },
        ],
      },
      {
        type: "text",
        heading: "How we communicate about evidence",
        id: "evidence",
        paragraphs: [
          "We label treatments as established, emerging or experimental. For example, " + EAU_PRP + " We do not guarantee outcomes, and we do not publish unverified success rates.",
        ],
      },
      { type: "doctor" },
      { type: "location" },
      { type: "international" },
      { type: "cta", title: "Speak to the Clinic", text: "Start with a confidential message or form.", label: "Speak to the Clinic", whatsapp: true },
    ],
    related: ["/dr-niyazi-umut-ozdemir", "/editorial-policy", "/evidence-methodology", "/international-patients"],
  },
  {
    path: "/international-patients",
    metaTitle: "Travelling to Antalya for ED Treatment | UZ Clinic",
    description:
      "How international patients are assessed before travelling to Antalya for ED treatment: what to send, planning, timing, follow-up and coordination.",
    h1: "Travelling to Antalya for ED Treatment",
    eyebrow: "International patients",
    kind: "money",
    treatment: "not-sure",
    medical: true,
    answer: {
      q: "How do international patients get ED treatment at UZ Clinic Antalya?",
      a: "International patients start with a confidential remote review: you send your history and any reports, a patient coordinator contacts you, and the urologist advises whether and how to proceed. Travel is arranged only once a plan makes medical sense, and treatment follows an in-person assessment with written consent and a follow-up plan.",
    },
    ctaLabel: "Send Your Case Before You Travel",
    modified: DATE,
    priority: 0.8,
    blocks: [
      {
        type: "steps",
        heading: "The international patient process",
        id: "process",
        steps: [
          { title: "Consultation process", text: "Start with the form or WhatsApp. A patient coordinator contacts you in your preferred way." },
          { title: "Assessment before travelling", text: "The clinic reviews your history, medicines and reports remotely, and may ask for further information." },
          { title: "Treatment planning", text: "If treatment may be appropriate, the plan, evidence, risks and alternatives are explained before you decide." },
          { title: "Travel timing", text: "The coordinator advises on timing based on your plan, for example the schedule for a multi-session course." },
          { title: "In-person assessment", text: "The urologist examines you and confirms the plan. You can still decide not to proceed." },
          { title: "Follow-up", text: "You receive written aftercare, a contact for questions and a follow-up plan, including after you return home." },
        ],
      },
      {
        type: "text",
        heading: "What information to send",
        id: "send",
        bullets: [
          "Your age, how long you have had ED and the main problem.",
          "Medicines and ED treatments you have tried.",
          "Medical history: diabetes, blood pressure, heart disease, prostate or pelvic surgery, Peyronie's disease.",
          "Recent blood tests or a penile Doppler ultrasound report, if available.",
        ],
      },
      { type: "cta", title: "Send Your Case Before You Travel", text: "Share your information confidentially and the clinic will tell you the best next step.", label: "Send Your Case Before You Travel" },
      { type: "location" },
      {
        type: "callout",
        tone: "info",
        title: "Medical question first",
        text: "Travel is the smallest part of the decision. The cause of your ED, the evidence for each option and the follow-up plan matter most. " + NO_GUARANTEE,
      },
      { type: "treatment-nav", heading: "Treatments you can ask about" },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Can I be assessed without travelling?", a: "You can start remotely. An in-person assessment is needed before treatment." },
      { q: "What languages are supported?", a: "Please ask the coordinator which languages are available when you make contact." },
      { q: "What if something goes wrong after I go home?", a: "You receive a contact and written warning signs. Seek urgent local care for emergencies, such as an erection lasting more than four hours." },
    ],
    related: ["/erectile-dysfunction-treatment-turkey", "/erectile-dysfunction-treatment-antalya", "/p-shot-turkey", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/patient-experiences",
    metaTitle: "Patient Experiences | UZ Clinic Antalya",
    description:
      "How UZ Clinic Antalya shares genuine patient experiences with consent, why individual results vary and how to ask about cases similar to yours.",
    h1: "Patient Experiences",
    eyebrow: "Patient experiences",
    kind: "trust",
    medical: false,
    parent: TRUST,
    answer: {
      q: "Are the patient experiences on this site genuine?",
      a: "Patient experiences are published only when they come from real patients who have given consent. They describe one person's experience. They are not guarantees, and results vary between patients. Experiences are never used in place of medical evidence.",
    },
    ctaLabel: "Ask About Cases Like Yours",
    modified: DATE,
    priority: 0.6,
    blocks: [
      { type: "rating" },
      { type: "stories", heading: "What patients say" },
      {
        type: "text",
        heading: "How we handle patient experiences",
        id: "policy",
        bullets: [
          "We publish only genuine experiences, with the patient's consent.",
          "We do not edit an experience to make a result sound stronger.",
          "Experiences are labelled by treatment, so you can see which relates to which.",
          "We do not use fake, paid or anonymous testimonials, or an invented rating.",
        ],
      },
      {
        type: "callout",
        tone: "caution",
        title: "Remember",
        text: "One person's result cannot predict yours. Suitability and expected benefit vary between patients and depend on the underlying cause. " + NO_GUARANTEE,
      },
      { type: "cta", title: "Ask About Experiences Similar to Yours", text: "Ask the clinic what to expect for your type of ED, and what the evidence says.", label: "Ask About Cases Like Yours", whatsapp: true },
    ],
    related: ["/p-shot", "/shockwave-therapy-ed", "/stem-cell-therapy-erectile-dysfunction", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/price",
    metaTitle: "P-Shot Price in Turkey | UZ Clinic Antalya",
    description:
      "The advertised P-Shot fee at UZ Clinic Antalya, what the treatment plan confirms in writing and what to ask when comparing any quotation.",
    h1: "P-Shot Price in Turkey",
    eyebrow: "Cost",
    kind: "money",
    treatment: "p-shot",
    medical: false,
    answer: {
      q: "How much does a P-Shot cost in Turkey?",
      a: "The advertised P-Shot treatment fee is £300, €300 or $300 depending on the billing currency. These are stated billing options, not live exchange-rate conversions. Your written treatment plan confirms what is included after assessment. Price is not evidence of outcome, and it never replaces assessment of whether treatment is suitable.",
    },
    ctaLabel: "Request an Itemised Quote",
    modified: DATE,
    priority: 0.8,
    schema: { therapy: "P-Shot (platelet-rich plasma injection)" },
    blocks: [
      { type: "price" },
      {
        type: "text",
        heading: "Questions to ask when comparing quotations",
        id: "compare",
        bullets: [
          "Is the quote for one session or a course?",
          "Who performs the treatment, and what are their qualifications?",
          "What is included: assessment, tests, anaesthetic, medication and follow-up?",
          "What is not included, such as travel, accommodation or extra sessions?",
          "What are the cancellation and refund terms if the doctor finds you unsuitable?",
        ],
      },
      { type: "cta", title: "Request an Itemised Quote", text: "Tell us about your case and the clinic will explain what a plan would include.", label: "Request an Itemised Quote", whatsapp: true },
      {
        type: "callout",
        tone: "info",
        title: "A higher price does not mean better outcomes",
        text: "A lower price does not prove that two protocols or providers are equivalent either. Compare itemised quotations, qualifications, consent and follow-up. PRP for ED remains experimental. " + EAU_PRP,
      },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Does the fee cover flights and hotel?", a: "Travel and accommodation are arranged separately. Your written plan confirms what the treatment fee includes." },
      { q: "Can I get a quote before travelling?", a: "Yes. Send your case and the coordinator explains the plan once the doctor has reviewed your information." },
    ],
    related: ["/p-shot", "/p-shot-turkey", "/international-patients", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/side-effects",
    metaTitle: "P-Shot Side Effects and Risks | UZ Clinic Antalya",
    description:
      "Possible P-Shot side effects, who should not have it, warning signs and when to seek urgent medical help after a penile PRP injection.",
    h1: "P-Shot Side Effects and Risks",
    eyebrow: "Safety",
    kind: "money",
    treatment: "p-shot",
    medical: true,
    evidence: "Experimental",
    answer: {
      q: "What are the side effects of the P-Shot?",
      a: "Reported side effects in studies have generally been minor: temporary pain, tenderness, bruising, redness or swelling. Bleeding, haematoma and infection are possible, and small trials cannot reliably quantify rare events or long-term effects. Using your own blood avoids rejection but does not make the procedure risk-free.",
    },
    ctaLabel: "Ask About P-Shot Safety",
    modified: DATE,
    priority: 0.7,
    blocks: [
      {
        type: "cards",
        heading: "Possible effects and risks",
        id: "risks",
        cols: 2,
        cards: [
          { title: "Expected or common", text: "Temporary injection pain, tenderness, bruising, redness or swelling." },
          { title: "Bleeding-related", text: "Higher risk with anticoagulants, antiplatelets or bleeding disorders." },
          { title: "Infection", text: "Possible with any injection if sterile technique is not followed." },
          { title: "Uncertain or uncommon", text: "Small trials cannot reliably quantify rare events or long-term effects on penile tissue." },
        ],
      },
      {
        type: "text",
        heading: "Discuss suitability before treatment",
        id: "suitability",
        bullets: [
          "Active infection, skin lesions or current genital symptoms.",
          "Bleeding disorders, low platelet counts or medicines that affect clotting.",
          "Cancer treatment, immune suppression or other major medical conditions.",
          "Allergy or prior reaction to local anaesthetic.",
          "Unexplained penile pain, curvature, a lump or suspected Peyronie's disease.",
        ],
      },
      {
        type: "callout",
        tone: "caution",
        title: "When to seek urgent help",
        text: "Seek urgent medical care for fever, spreading redness, pus, rapidly increasing swelling, severe or worsening pain, significant bleeding, difficulty urinating, loss of penile sensation or an erection lasting more than four hours.",
      },
      { type: "cta", title: "Ask the Urologist About Safety", text: "Questions about whether the P-Shot is safe for your health history? Send them before you decide.", label: "Ask About P-Shot Safety", whatsapp: true },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Is the P-Shot safe?", a: "Reported side effects have mostly been minor, but studies are small. The doctor explains risks and who should not have it." },
      { q: "What if I take blood thinners?", a: "Tell the doctor. Blood thinners can raise the risk of bleeding and may mean the P-Shot is unsuitable." },
    ],
    sources: ["eau2026", "masterson2023", "panunzio2024"],
    related: ["/p-shot", "/prp-for-erectile-dysfunction", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/ed-knowledge-hub",
    metaTitle: "Erectile Dysfunction Knowledge Hub | UZ Clinic Antalya",
    description:
      "Guides to ED causes, conditions and treatments: P-Shot, shockwave, stem cells, exosomes, diagnosis and penile rehabilitation, written for patients.",
    h1: "Erectile Dysfunction Knowledge Hub",
    eyebrow: "Education",
    kind: "article",
    treatment: "not-sure",
    medical: true,
    answer: {
      q: "Where can I learn about ED causes and treatments?",
      a: "This hub gathers patient guides on the causes of erectile dysfunction, related conditions, diagnostic tests and treatments, from established options to emerging and experimental therapies. Each guide explains the evidence in plain language and shows when specialist assessment is useful.",
    },
    ctaLabel: "Check Treatment Options",
    modified: DATE,
    priority: 0.8,
    blocks: [
      {
        type: "cards",
        heading: "Understand your ED",
        id: "conditions",
        cols: 3,
        cards: [
          { title: "Erectile dysfunction", text: "Causes, types and assessment.", href: "/erectile-dysfunction" },
          { title: "Vasculogenic ED", text: "Blood-flow related ED.", href: "/vasculogenic-erectile-dysfunction" },
          { title: "Venous leak", text: "When an erection fades.", href: "/venous-leak" },
          { title: "After prostate surgery", text: "Recovery and rehabilitation.", href: "/erectile-dysfunction-after-prostate-surgery" },
          { title: "Diabetes and ED", text: "How diabetes affects erections.", href: "/diabetes-erectile-dysfunction" },
          { title: "Testosterone and ED", text: "When low testosterone is the cause.", href: "/testosterone-ed" },
          { title: "Finasteride and sexual symptoms", text: "What regulators say.", href: "/post-finasteride-syndrome-ed" },
          { title: "ED over 50", text: "Early assessment.", href: "/erectile-dysfunction-over-50" },
          { title: "ED over 60", text: "Safe, realistic options.", href: "/erectile-dysfunction-over-60" },
        ],
      },
      {
        type: "cards",
        heading: "Diagnosis and treatment guides",
        id: "treatments",
        cols: 3,
        cards: [
          { title: "Penile Doppler ultrasound", text: "Testing blood flow.", href: "/penile-doppler-ultrasound" },
          { title: "P-Shot (PRP)", text: "Procedure, suitability and evidence.", href: "/p-shot" },
          { title: "Shockwave therapy (EdSWT)", text: "Protocol and patient selection.", href: "/shockwave-therapy-ed" },
          { title: "Stem cell therapy", text: "Experimental regenerative option.", href: "/stem-cell-therapy-erectile-dysfunction" },
          { title: "Exosome therapy", text: "Investigational, with limited evidence.", href: "/exosome-therapy-erectile-dysfunction" },
          { title: "P-Shot vs Viagra", text: "Established vs experimental.", href: "/p-shot-vs-viagra" },
          { title: "ED treatment options compared", text: "All options side by side.", href: "/ed-treatment-options" },
          { title: "Penile rehabilitation", text: "Structured recovery plans.", href: "/penile-rehabilitation" },
          { title: "Penile implant", text: "A surgical option.", href: "/penile-implant" },
        ],
      },
      { type: "cta", title: "Not Sure Where to Start?", text: "Send your case and the clinic can advise which guides and options are relevant.", label: "Check Treatment Options", whatsapp: true },
    ],
    related: ["/ed-treatment-options", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/editorial-policy",
    metaTitle: "Editorial Policy | UZ Clinic Antalya",
    description:
      "How medical content on this site is selected, sourced, written, reviewed and corrected, and how it is separated from commercial calls to action.",
    h1: "Editorial Policy",
    eyebrow: "Trust and transparency",
    kind: "trust",
    medical: false,
    parent: TRUST,
    answer: {
      q: "How is the medical content on this site produced?",
      a: "Content is based on clinical guidelines, regulators, systematic reviews and controlled trials. It separates proposed mechanisms from demonstrated outcomes, labels treatments as established, emerging or experimental, and keeps commercial calls to action from contradicting the evidence.",
    },
    ctaLabel: "Ask the Urologist",
    modified: DATE,
    priority: 0.4,
    blocks: [
      {
        type: "text",
        heading: "Our principles",
        bullets: [
          "Topic selection: we prioritise questions that affect diagnosis, treatment choice, safety, informed consent and cost.",
          "Sources: guidelines and regulators first, then systematic reviews and controlled trials. Anonymous testimonials and forum posts are not medical evidence.",
          "Claims: we distinguish proposed mechanisms from demonstrated patient outcomes.",
          "Medical review: pages show an update date. A page is described as medically reviewed only after the physician has actually reviewed it.",
          "Commercial separation: calls to action must not imply diagnosis, eligibility or guaranteed outcomes.",
          "Corrections: substantive corrections update the page's modification date.",
        ],
      },
    ],
    related: ["/evidence-methodology", "/about", "/dr-niyazi-umut-ozdemir"],
  },
  {
    path: "/evidence-methodology",
    metaTitle: "Evidence Methodology | UZ Clinic Antalya",
    description:
      "How guidelines, systematic reviews, trials and clinic observations are ranked and how uncertainty is communicated about ED treatments.",
    h1: "Evidence Methodology",
    eyebrow: "Trust and transparency",
    kind: "trust",
    medical: false,
    parent: TRUST,
    answer: {
      q: "How is the strength of evidence judged?",
      a: "We rank sources from clinical guidelines and regulators, through systematic reviews and randomised trials, to observational studies, expert commentary and clinic or patient anecdotes. When sources disagree, we report the disagreement and prioritise the current guideline position.",
    },
    ctaLabel: "Ask the Urologist",
    modified: DATE,
    priority: 0.4,
    blocks: [
      {
        type: "table",
        heading: "Source hierarchy",
        caption: "Evidence levels used on this site",
        headers: ["Level", "Source type", "How it is used"],
        rows: [
          ["1", "Clinical guidelines and regulators", "Current recommendations, safety warnings and regulatory framing."],
          ["2", "Systematic reviews and meta-analyses", "Total evidence and its heterogeneity."],
          ["3", "Randomised controlled trials", "Comparative efficacy and adverse events, with limits stated."],
          ["4", "Prospective or observational studies", "Used cautiously where stronger evidence is absent."],
          ["5", "Expert commentary", "Context, not to override primary evidence."],
          ["6", "Clinic observations and patient anecdotes", "Can raise questions but cannot establish safety or effectiveness."],
        ],
      },
      {
        type: "text",
        heading: "When sources disagree",
        paragraphs: ["We report the disagreement and prioritise the current guideline position. For PRP and ED, positive trials exist alongside a negative placebo-controlled trial, and protocols vary, so we describe PRP as experimental rather than proven."],
      },
    ],
    related: ["/editorial-policy", "/about"],
  },
  {
    path: "/privacy",
    metaTitle: "Privacy Notice | UZ Clinic Antalya",
    description:
      "How UZ Clinic Antalya handles information from the assessment form, WhatsApp, email and website analytics, and your rights under KVKK and GDPR.",
    h1: "Privacy Notice",
    eyebrow: "Privacy",
    kind: "legal",
    medical: false,
    answer: {
      q: "How is my information used?",
      a: "Information you send through the assessment form, WhatsApp or email is used to review your enquiry and contact you about assessment. Health information is processed only with your explicit consent. Analytics cookies are used only if you accept them, and no health information is sent to analytics.",
    },
    ctaLabel: "Ask the Urologist",
    modified: DATE,
    priority: 0.2,
    blocks: [
      {
        type: "text",
        heading: "Who is responsible for your information",
        id: "controller",
        paragraphs: [
          "The data controller is UZ Clinic Antalya, the practice of Op. Dr. Niyazi Umut Özdemir, Urological Surgeon, at Fener Mah., Bülent Ecevit Blv., Kanyon Plaza No:23, Kat:4, Daire:7, 07160 Muratpaşa / Antalya, Turkey.",
          "For any privacy question or request, email penilerehab@gmail.com or message the clinic on WhatsApp.",
        ],
      },
      {
        type: "text",
        heading: "What we collect",
        id: "collect",
        bullets: [
          "Assessment form answers: age, symptoms, how long you have had them, treatments tried, medical history, treatment interest, country, travel timing, contact preference, name, WhatsApp number and email.",
          "Messages, phone calls and emails you send us, including any reports you choose to share.",
          "Technical data needed to run and protect the website, such as your IP address in server logs.",
          "Website usage data (pages viewed, source of your visit), only if you accept analytics cookies.",
        ],
      },
      {
        type: "text",
        heading: "Why we use it, and on what basis",
        id: "purposes",
        bullets: [
          "To review your enquiry and contact you about next steps, and to prepare a consultation if you go ahead. Health information is special-category data, so we ask for your explicit consent (KVKK Article 6; UK and EU GDPR Article 9(2)(a)). You give it with the first tick box on the form.",
          "To transfer your enquiry to service providers that may be outside Turkey, for the same purpose. We ask for your separate explicit consent for this, with the second tick box.",
          "To understand how the website is used and improve it, with your consent to analytics cookies.",
          "To keep the website secure and to meet legal obligations, including those that apply to medical records if you become a patient.",
        ],
        note: "You can withdraw consent at any time by contacting us. Withdrawal does not affect processing carried out before it.",
      },
      {
        type: "text",
        heading: "Who receives your information",
        id: "recipients",
        paragraphs: [
          "Your enquiry is seen by the clinic team that handles patient enquiries. It is also processed by service providers that run our systems, such as website hosting, email delivery and messaging (WhatsApp is operated by Meta). We may disclose information to public authorities where the law requires it.",
          "We do not sell your information. Health information is never sent to advertising or analytics platforms.",
        ],
      },
      {
        type: "text",
        heading: "Transfers outside Turkey",
        id: "transfers",
        paragraphs: [
          "Some providers process data on servers outside Turkey and, for UK and EU patients, outside the UK or European Economic Area. We transfer your information abroad only with your explicit consent and, where the law requires, with additional safeguards.",
        ],
      },
      {
        type: "text",
        heading: "How long we keep it",
        id: "retention",
        paragraphs: [
          "We keep enquiry information only as long as needed to respond to you and, if you become a patient, for the period the law requires for medical records. When it is no longer needed, we delete or anonymise it.",
        ],
      },
      {
        type: "text",
        heading: "Your rights",
        id: "rights",
        paragraphs: [
          "Under Turkish Law No. 6698 (KVKK), Article 11, you may ask whether your data is processed and for information about it, learn the purpose and whether it is used appropriately, learn who it has been passed to, ask for correction, ask for deletion or destruction, ask for those actions to be notified to recipients, object to a result produced solely by automated analysis, and claim compensation for loss caused by unlawful processing.",
          "If UK or EU GDPR applies to you, you may also ask for access, rectification, erasure, restriction, portability and object to processing.",
          "Email penilerehab@gmail.com. We aim to reply within 30 days. You may also complain to the Turkish Personal Data Protection Authority (KVKK), or, if you live in the UK or EU, to the Information Commissioner's Office or your local data-protection authority.",
        ],
      },
      {
        type: "text",
        heading: "Cookies and analytics",
        id: "cookies",
        paragraphs: [
          "If analytics is enabled, we use Google Analytics 4 with consent settings that start as denied. Analytics cookies are set only if you accept them, and you can decline. Your choice is stored in your browser. We also keep the source of your visit (for example the website or campaign that sent you) for the current browser session so we can understand which pages lead to enquiries.",
        ],
      },
      {
        type: "text",
        heading: "Security, messaging and emergencies",
        id: "security",
        paragraphs: [
          "We take reasonable technical and organisational measures to protect your information, and the website uses encrypted connections. No method of transmission is completely secure, so share only what you are comfortable sending by WhatsApp or email.",
          "Do not use the form, WhatsApp or email for emergencies. Contact local emergency services instead.",
        ],
      },
      {
        type: "text",
        heading: "Age and changes",
        id: "changes",
        paragraphs: [
          "This service is for adults. Do not submit the form if you are under 18.",
          "We may update this notice. The date of the latest update is shown on this page: 2 October 2026.",
        ],
      },
    ],
    related: ["/erectile-dysfunction-assessment", "/about"],
  },
];
