import { DATE, EAU_PRP, NO_GUARANTEE } from "../shared";
import type { PageDef } from "../types";

const PARENT = { name: "Erectile dysfunction", path: "/erectile-dysfunction" };

export const conditionPages: PageDef[] = [
  {
    path: "/vasculogenic-erectile-dysfunction",
    metaTitle: "Vasculogenic Erectile Dysfunction: Causes and Treatment",
    description:
      "Vasculogenic ED is erectile dysfunction caused by blood-flow problems. Symptoms, causes, how it is diagnosed and which treatments may be relevant.",
    h1: "Vasculogenic Erectile Dysfunction (Blood-Flow Related ED)",
    eyebrow: "Condition guide",
    kind: "condition",
    treatment: "shockwave",
    medical: true,
    evidence: "Established",
    parent: PARENT,
    answer: {
      q: "What is vasculogenic ED?",
      a: "Vasculogenic erectile dysfunction is ED caused by problems with blood flow to or within the penis. An erection needs enough blood to flow in through the arteries and to stay trapped in the erectile tissue. If arteries are narrowed or the tissue cannot hold blood, erections can be weaker or fade. It is one of the most common physical causes of ED.",
    },
    takeaways: [
      "It covers arterial insufficiency (not enough blood in) and cavernosal or venous leak (blood not retained).",
      "Risk factors include diabetes, high blood pressure, high cholesterol, smoking and age.",
      "Penile Doppler ultrasound can assess blood flow in selected men.",
    ],
    ctaLabel: "Check Treatment Options for Blood-Flow ED",
    modified: DATE,
    priority: 0.9,
    schema: { condition: "Vasculogenic erectile dysfunction" },
    blocks: [
      {
        type: "cards",
        heading: "Two blood-flow patterns",
        id: "types",
        cols: 2,
        cards: [
          { title: "Arterial insufficiency", text: "Narrowed or stiff arteries reduce blood inflow, so erections may be less firm or slow to develop." },
          { title: "Cavernosal insufficiency (venous leak)", text: "Blood enters but is not retained, so the erection may start and then fade.", href: "/venous-leak" },
        ],
      },
      {
        type: "text",
        heading: "Common causes and risk factors",
        id: "causes",
        bullets: [
          "Diabetes and high blood sugar.",
          "High blood pressure and high cholesterol.",
          "Smoking and obesity.",
          "Heart and blood-vessel disease. ED can be an early warning sign, so a health review is worthwhile.",
          "Age-related changes in the penile tissue.",
        ],
      },
      { type: "cta", title: "Find Out If Your ED Is Blood-Flow Related", text: "Send your history. The urologist can advise whether a Doppler assessment may help.", label: "Find Out If Your ED Is Blood-Flow Related" },
      {
        type: "text",
        heading: "How it is diagnosed",
        id: "diagnosis",
        paragraphs: [
          "Diagnosis starts with history and examination. Blood tests check diabetes, cholesterol and testosterone. Penile Doppler ultrasound can assess blood flow in selected men.",
        ],
      },
      {
        type: "cards",
        heading: "Treatment options that may be relevant",
        id: "treatment",
        cols: 2,
        intro: "Which one fits depends on your assessment. " + NO_GUARANTEE,
        cards: [
          { title: "Risk-factor management", text: "Blood sugar, blood pressure, cholesterol, smoking and exercise are the foundation, and can improve ED in some men." },
          { title: "PDE5 tablets", text: "First-line for many men, unless contraindicated." },
          { title: "Shockwave therapy (EdSWT)", text: "Emerging. A weak EAU recommendation for selected men with vasculogenic ED.", href: "/shockwave-therapy-ed" },
          { title: "Regenerative options", text: "PRP, stem cells and exosomes are experimental and are discussed only after assessment.", href: "/ed-treatment-options" },
        ],
      },
      { type: "comparison", highlight: ["shockwave", "pde5", "p-shot"] },
      { type: "cta", title: "Ask the Urologist About Blood-Flow ED", text: "Not sure which option is relevant? Message the clinic.", label: "Ask the Urologist", whatsapp: true },
      { type: "doctor" },
    ],
    faqs: [
      { q: "What is vasculogenic ED?", a: "ED caused by reduced blood inflow into the penis or reduced ability of the penis to hold blood." },
      { q: "Can vasculogenic ED be reversed?", a: "Some men improve with risk-factor control and treatment, but it depends on the cause and severity. No outcome can be promised." },
      { q: "Is shockwave therapy for vasculogenic ED?", a: "Yes, it is intended primarily for vasculogenic ED, with careful patient selection. The EAU recommendation is weak and for selected men." },
    ],
    sources: ["eau2026", "aua2018"],
    related: ["/venous-leak", "/penile-doppler-ultrasound", "/shockwave-therapy-ed", "/diabetes-erectile-dysfunction", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/venous-leak",
    metaTitle: "Venous Leak ED: Symptoms, Diagnosis and Options",
    description:
      "Venous leak (cavernosal insufficiency) can make an erection fade. Symptoms, how penile Doppler diagnoses it and which options may be discussed.",
    h1: "Venous Leak and Erectile Dysfunction",
    eyebrow: "Condition guide",
    kind: "condition",
    treatment: "not-sure",
    medical: true,
    evidence: "Mixed",
    parent: PARENT,
    answer: {
      q: "What is venous leak?",
      a: "Venous leak, also called cavernosal insufficiency or veno-occlusive dysfunction, means the penis cannot hold blood well enough to keep an erection. The erection may start and then fade. Symptoms alone do not confirm it. A urologist assesses it, often with penile Doppler ultrasound.",
    },
    takeaways: [
      "A typical pattern is an erection that is achieved and then lost.",
      "Similar symptoms can have other causes, so it needs medical assessment.",
      "There is no established cure from regenerative injections. " + EAU_PRP,
    ],
    ctaLabel: "Check Treatment Options for Venous Leak",
    modified: DATE,
    priority: 0.9,
    schema: { condition: "Venous leak (veno-occlusive erectile dysfunction)" },
    blocks: [
      {
        type: "text",
        heading: "How an erection stays firm",
        id: "how",
        paragraphs: [
          "An erection needs blood to flow in and the veins that drain the penis to be compressed, so blood stays in. In venous leak, this sealing mechanism does not work well.",
        ],
      },
      {
        type: "text",
        heading: "Symptoms that may suggest it",
        id: "symptoms",
        bullets: [
          "An erection that starts but cannot be maintained.",
          "Needing more stimulation or losing the erection quickly.",
          "Poor response to tablets.",
        ],
        note: "These patterns are not specific. Arterial, nerve, hormonal and psychological causes can look similar.",
      },
      { type: "cta", title: "Get Your Symptoms Reviewed by a Urologist", text: "Send your history and any Doppler results. The clinic can tell you what to do next.", label: "Check Treatment Options for Venous Leak" },
      {
        type: "text",
        heading: "How it is diagnosed",
        id: "diagnosis",
        paragraphs: [
          "Penile Doppler (duplex) ultrasound, usually after an injection that induces an erection, measures blood flow in and out of the penis. Some centres also use more specialised tests in selected men.",
        ],
      },
      {
        type: "cards",
        heading: "Options a urologist may discuss",
        id: "options",
        cols: 2,
        cards: [
          { title: "Risk-factor control and PDE5 optimisation", text: "Correct use and dosing of tablets, and management of diabetes, blood pressure and lifestyle." },
          { title: "Vacuum devices and injections", text: "Established options that can produce an erection regardless of the cause." },
          { title: "Shockwave and regenerative therapies", text: "Evidence in confirmed venous leak is limited. They are discussed only when appropriate, and are not claimed to cure it." },
          { title: "Penile implant", text: "May be discussed for severe ED that does not respond to other options.", href: "/penile-implant" },
        ],
      },
      {
        type: "callout",
        tone: "caution",
        title: "Be cautious about claims",
        text: "No regenerative treatment is established as a cure for venous leak, and venous surgery is not a routine solution for most men. Ask any provider for the evidence behind their recommendation.",
      },
      { type: "comparison", highlight: ["pde5", "injections", "implant"] },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Can venous leak be cured?", a: "No treatment is established as a cure. Management focuses on options that help you achieve a usable erection. The urologist explains what is realistic." },
      { q: "Can P-Shot treat venous leak?", a: "No evidence establishes PRP as a treatment for confirmed venous leak. It remains experimental." },
      { q: "How is venous leak confirmed?", a: "Usually through penile Doppler ultrasound and clinical assessment by a urologist." },
    ],
    sources: ["eau2026", "aua2018", "masterson2023"],
    related: ["/vasculogenic-erectile-dysfunction", "/penile-doppler-ultrasound", "/ed-treatment-options", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/erectile-dysfunction-after-prostate-surgery",
    metaTitle: "ED After Prostate Surgery: Recovery and Rehabilitation",
    description:
      "Why erectile dysfunction is common after prostatectomy, what recovery depends on and which rehabilitation options a urologist may discuss.",
    h1: "Erectile Dysfunction After Prostate Surgery",
    eyebrow: "Post-surgical ED",
    kind: "condition",
    treatment: "rehabilitation",
    medical: true,
    evidence: "Established",
    parent: PARENT,
    answer: {
      q: "Is erectile dysfunction common after prostate surgery?",
      a: "Yes. Radical prostatectomy can affect the nerves and blood vessels that control erections, even with nerve-sparing surgery. Recovery varies with your function before surgery, age, surgical factors and time, and can take many months. A rehabilitation plan from a urologist can help structure recovery, but no outcome can be guaranteed.",
    },
    takeaways: [
      "Nerve recovery can take many months.",
      "Early, structured rehabilitation is a common approach, individualised by the doctor.",
      "Evidence for PRP after prostatectomy is insufficient to replace guideline-supported care.",
    ],
    ctaLabel: "Ask About Post-Prostatectomy Rehabilitation",
    modified: DATE,
    priority: 0.85,
    schema: { condition: "Erectile dysfunction after prostatectomy" },
    blocks: [
      {
        type: "text",
        heading: "Why recovery varies",
        id: "why",
        bullets: [
          "Baseline erectile function, age and cardiovascular health influence recovery.",
          "Whether one or both nerve bundles could be spared matters, but nerve-sparing does not guarantee preserved erections.",
          "Lack of spontaneous erections early on does not alone predict the final outcome.",
        ],
      },
      {
        type: "cards",
        heading: "Rehabilitation and treatment options",
        id: "options",
        cols: 2,
        cards: [
          { title: "PDE5 tablets", text: "May be used early in some men, if appropriate." },
          { title: "Vacuum erection devices", text: "Can support penile blood flow and tissue health." },
          { title: "Intracavernosal injections", text: "Produce an erection and may be used when tablets are not enough." },
          { title: "Implant", text: "A surgical option when other treatments fail.", href: "/penile-implant" },
        ],
      },
      { type: "cta", title: "Plan Your Recovery With a Urologist", text: "Send your surgery details and what you have tried so far. The clinic can advise on next steps.", label: "Ask About Post-Prostatectomy Rehabilitation" },
      {
        type: "callout",
        tone: "evidence",
        title: "Where regenerative and shockwave therapy fit",
        text: "Small studies have explored restorative approaches after prostatectomy, but evidence is not strong enough to describe PRP as nerve regeneration or a proven route to recovery. " + EAU_PRP,
      },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Will my erections return after prostatectomy?", a: "It varies. Many men regain some function over time, but outcomes cannot be predicted or guaranteed." },
      { q: "When should rehabilitation start?", a: "Timing is individualised. Ask your surgeon or urologist, and send your details to the clinic if you want a second opinion." },
    ],
    sources: ["eau2026", "aua2018"],
    related: ["/penile-rehabilitation", "/penile-implant", "/ed-treatment-options", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/diabetes-erectile-dysfunction",
    metaTitle: "Diabetes and Erectile Dysfunction: Assessment and Options",
    description:
      "How diabetes can cause erectile dysfunction through blood vessels and nerves, what to assess and which treatments may be relevant.",
    h1: "Diabetes and Erectile Dysfunction",
    eyebrow: "Condition guide",
    kind: "condition",
    treatment: "not-sure",
    medical: true,
    evidence: "Established",
    parent: PARENT,
    answer: {
      q: "Can diabetes cause erectile dysfunction?",
      a: "Yes. Diabetes can damage blood vessels and nerves and often coexists with high blood pressure and cholesterol, all of which can affect erections. ED may also be an early sign of poorly controlled diabetes. Managing blood sugar and cardiovascular risk matters alongside any ED treatment.",
    },
    ctaLabel: "Ask About Diabetes-Related ED",
    modified: DATE,
    priority: 0.8,
    schema: { condition: "Diabetes-related erectile dysfunction" },
    blocks: [
      {
        type: "text",
        heading: "How diabetes affects erections",
        id: "how",
        bullets: [
          "Long-term high blood sugar can damage small blood vessels and reduce endothelial function.",
          "Neuropathy can interfere with sexual sensation and nerve signalling.",
          "Diabetes often coexists with high blood pressure, high cholesterol, obesity and heart disease.",
          "Low testosterone, depression and medicines can also contribute.",
        ],
      },
      { type: "cta", title: "Get Specialist Advice for Diabetic ED", text: "Share your diabetes history and medicines. The urologist can advise which options may be relevant.", label: "Ask About Diabetes-Related ED" },
      {
        type: "text",
        heading: "Assessment and treatment options",
        id: "options",
        paragraphs: [
          "The doctor reviews blood sugar control, cardiovascular risk, medicines and hormones where indicated. PDE5 tablets are commonly first-line. Vacuum devices, injections and other therapies may be used when tablets are unsuitable or insufficient. Shockwave therapy may be considered in selected men with a blood-flow pattern.",
        ],
      },
      {
        type: "callout",
        tone: "evidence",
        title: "Regenerative treatments in diabetic ED",
        text: "PRP and other regenerative approaches have not been established for diabetic ED. A claim that they repair diabetic nerves or reverse diabetic damage goes beyond current evidence.",
      },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Does better blood sugar control help ED?", a: "It can help protect blood vessels and nerves, but it cannot be promised to restore erections." },
      { q: "Are tablets safe with diabetes?", a: "Often yes, but the doctor checks your heart health and other medicines first." },
    ],
    sources: ["eau2026", "aua2018"],
    related: ["/vasculogenic-erectile-dysfunction", "/shockwave-therapy-ed", "/erectile-dysfunction-assessment", "/ed-treatment-options"],
  },
  {
    path: "/erectile-dysfunction-over-50",
    metaTitle: "Erectile Dysfunction Over 50: Causes and Early Assessment",
    description:
      "ED over 50 is common but not something to accept without checking. Causes, early warning signs and what an assessment can reveal.",
    h1: "Erectile Dysfunction Over 50",
    eyebrow: "Age-related ED",
    kind: "condition",
    treatment: "not-sure",
    medical: true,
    evidence: "Established",
    parent: PARENT,
    answer: {
      q: "Is erectile dysfunction normal after 50?",
      a: "ED becomes more common with age, but it is not something you simply have to accept. After 50, ED is often linked to blood-vessel changes, diabetes, high blood pressure, cholesterol, medicines or lower testosterone, and it can be an early sign of heart disease. An assessment can find the cause and guide treatment.",
    },
    ctaLabel: "Check If You're Suitable",
    modified: DATE,
    priority: 0.7,
    schema: { condition: "Age-related erectile dysfunction" },
    blocks: [
      {
        type: "text",
        heading: "Common reasons for ED in your 50s",
        id: "reasons",
        bullets: [
          "Early blood-vessel changes that reduce blood flow.",
          "Diabetes and metabolic risk, high blood pressure and high cholesterol.",
          "Medicines, including some for blood pressure or mood.",
          "Lower testosterone in some men.",
          "Stress, sleep problems and relationship factors.",
        ],
      },
      { type: "cta", title: "Find Out What Is Behind Your ED", text: "A confidential assessment can separate a treatable cause from normal ageing.", label: "Find Out What May Be Causing Your ED" },
      {
        type: "text",
        heading: "Why not wait?",
        id: "why-assess",
        paragraphs: [
          "New or worsening ED can come before heart problems. Checking blood pressure, glucose, cholesterol and hormones is worthwhile even if your main goal is better erections.",
        ],
      },
      { type: "comparison", heading: "Options a urologist may discuss" },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Will tablets work at my age?", a: "Many men benefit, unless contraindicated. The doctor checks your health and medicines first." },
      { q: "Do I need a Doppler scan?", a: "Not for everyone. The doctor decides after history and examination." },
    ],
    sources: ["eau2026", "aua2018"],
    related: ["/erectile-dysfunction-over-60", "/erectile-dysfunction", "/penile-doppler-ultrasound", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/erectile-dysfunction-over-60",
    metaTitle: "Erectile Dysfunction Over 60: Safe, Realistic Options",
    description:
      "ED over 60 often involves other health conditions and medicines. What to check, what is realistic and how a urologist chooses safe options.",
    h1: "Erectile Dysfunction Over 60",
    eyebrow: "Age-related ED",
    kind: "condition",
    treatment: "not-sure",
    medical: true,
    evidence: "Established",
    parent: PARENT,
    answer: {
      q: "Can erectile dysfunction be treated after 60?",
      a: "Often, yes. Options depend on your general health, heart condition, medicines and what you want from treatment. After 60, safety checks matter more because other conditions and medicines, such as nitrates, can limit choices. A urologist can explain which options are safe and realistic for you.",
    },
    ctaLabel: "Check If You're Suitable",
    modified: DATE,
    priority: 0.7,
    schema: { condition: "Age-related erectile dysfunction" },
    blocks: [
      {
        type: "text",
        heading: "What matters most after 60",
        id: "matters",
        bullets: [
          "Heart health, because sexual activity and some ED medicines need a safe cardiac profile.",
          "Medicines: PDE5 tablets must not be combined with nitrates.",
          "Prostate health and any previous surgery or radiotherapy.",
          "Diabetes, nerve health and testosterone.",
          "Realistic goals, discussed openly with your partner if you wish.",
        ],
      },
      { type: "cta", title: "Ask Whether Treatment Is Safe for You", text: "Share your health and medicines. The urologist can advise on safe options.", label: "Ask the Urologist", whatsapp: true },
      { type: "comparison", heading: "Options a urologist may discuss" },
      {
        type: "callout",
        tone: "caution",
        title: "Seek medical help urgently if",
        text: "You have chest pain, breathlessness or new neurological symptoms, or an erection lasting more than four hours.",
      },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Is a penile implant an option?", a: "It can be for severe ED when other options have failed, after surgical assessment." },
      { q: "Are regenerative treatments suitable?", a: "They are experimental. A doctor decides after assessment, and established options are discussed first." },
    ],
    sources: ["eau2026", "aua2018"],
    related: ["/erectile-dysfunction-over-50", "/penile-implant", "/ed-treatment-options", "/erectile-dysfunction-assessment"],
  },
];
