import { ASSESS_STEPS, DATE, EAU_PRP, NO_GUARANTEE } from "../shared";
import type { PageDef } from "../types";

export const corePages: PageDef[] = [
  {
    path: "/erectile-dysfunction",
    metaTitle: "Erectile Dysfunction: Causes and Specialist Assessment",
    description:
      "Understand the main causes of erectile dysfunction, why the cause matters and how a urologist assesses it. Send your case for a confidential review.",
    h1: "Erectile Dysfunction: Causes, Types and Specialist Assessment",
    eyebrow: "Condition guide",
    kind: "condition",
    medical: true,
    evidence: "Established",
    answer: {
      q: "What is erectile dysfunction?",
      a: "Erectile dysfunction (ED) is the repeated difficulty getting or keeping an erection firm enough for satisfactory sexual activity. It is common. It often has a physical cause, such as reduced blood flow, nerve damage or a hormonal problem, and it can sometimes be an early sign of heart or metabolic disease. The right treatment depends on the cause.",
    },
    lead: "Many men wait years before asking for help. A confidential specialist assessment can show which type of ED you may have and which options are worth considering.",
    takeaways: [
      "ED is a symptom with several possible causes, not a single condition.",
      "Blood-flow problems are one of the most common physical causes.",
      "New or worsening ED can be linked to heart disease, diabetes or hormone problems, so assessment matters.",
      "You do not need to know which treatment you need before contacting the clinic.",
    ],
    ctaLabel: "Check If You're Suitable",
    modified: DATE,
    priority: 1,
    schema: { condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "cards",
        heading: "What kind of erection problem do you have?",
        id: "symptoms",
        intro: "These patterns can point towards different causes. Only an assessment can confirm which one applies to you.",
        cards: [
          { id: "difficulty-getting-an-erection", title: "Difficulty getting an erection", text: "Often linked to reduced blood inflow, nerve problems, hormones or anxiety. Morning or night erections can help show whether the cause is more physical or psychological." },
          { id: "difficulty-maintaining-an-erection", title: "Difficulty keeping an erection", text: "An erection that starts but fades quickly can be related to the penis not holding blood effectively (venous leak) or to other blood-flow problems.", href: "/venous-leak" },
          { id: "reduced-hardness", title: "Reduced hardness", text: "Less firm erections are often a blood-flow (vasculogenic) pattern, especially with diabetes, high blood pressure, smoking or high cholesterol.", href: "/vasculogenic-erectile-dysfunction" },
          { id: "reduced-sensitivity", title: "Reduced penile sensitivity", text: "Reduced feeling can point to nerve involvement, for example after pelvic surgery or with diabetic neuropathy. It deserves a proper medical review." },
          { id: "sudden-onset", title: "Sudden-onset ED", text: "ED that starts suddenly can follow a new medicine, stress, injury, a hormone problem or a health event. See a doctor promptly, particularly if you also have chest symptoms or neurological symptoms." },
          { id: "tablets-not-working", title: "ED despite Viagra or Cialis", text: "Tablets may not work well if the dose, timing or contraindications are wrong, or if the underlying cause needs a different approach.", href: "/ed-treatment-options" },
        ],
      },
      {
        type: "cards",
        heading: "Not all erectile dysfunction has the same cause",
        id: "causes",
        intro: "Many men have more than one contributing factor. Identifying the main one helps the doctor choose which options may be relevant.",
        cards: [
          { title: "Vasculogenic ED", text: "Reduced blood flow into or retention of blood in the penis. This is the most common physical group.", href: "/vasculogenic-erectile-dysfunction" },
          { title: "Arterial insufficiency", text: "Narrowed or stiff arteries limit the blood that can enter the penis. It often shares risk factors with heart disease." },
          { title: "Cavernosal insufficiency (venous leak)", text: "The penile tissue cannot trap blood effectively, so the erection fades.", href: "/venous-leak" },
          { title: "Neurogenic ED", text: "Nerve signals are affected, for example by diabetes, spinal problems or pelvic surgery." },
          { title: "Hormonal ED", text: "Low testosterone or other hormonal problems can reduce desire and erections.", href: "/testosterone-ed" },
          { title: "Drug-related ED", text: "Some medicines can affect erections, including some antidepressants, blood-pressure medicines and 5-alpha-reductase inhibitors." },
          { title: "Post-surgical (iatrogenic) ED", text: "Surgery or radiotherapy in the pelvis, especially for prostate cancer, can affect nerves and blood vessels.", href: "/erectile-dysfunction-after-prostate-surgery" },
          { title: "Psychogenic ED", text: "Anxiety, depression, stress and relationship factors. They can occur alone or alongside a physical cause." },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Organic or psychogenic ED?",
        text: "Clues such as firm morning erections, situational problems or a sudden start can suggest a psychological component. Gradual loss of hardness over time, or ED with diabetes or heart disease, can suggest a physical cause. These are only clues. A medical history, examination and, where useful, penile Doppler ultrasound give a clearer picture.",
      },
      {
        type: "cta",
        title: "Find Out What May Be Causing Your ED",
        text: "Send your symptoms and history confidentially. The clinic can tell you which assessment steps and treatment options may be relevant.",
        label: "Find Out What May Be Causing Your ED",
      },
      {
        type: "steps",
        heading: "How a specialist ED assessment works",
        id: "assessment",
        steps: [
          { title: "History", text: "Your symptoms, medical conditions, medicines, surgeries, lifestyle and previous treatments." },
          { title: "Examination", text: "A focused physical examination, including blood pressure and genital examination where appropriate." },
          { title: "Tests when useful", text: "Blood tests such as glucose or HbA1c, lipids and morning testosterone. Penile Doppler ultrasound can assess blood flow in selected men." },
          { title: "Cause-based plan", text: "The doctor explains which options may be relevant to the likely cause, including established treatments and any emerging therapies." },
        ],
      },
      { type: "comparison", heading: "ED treatment options at a glance", intro: "The most appropriate treatment depends on the underlying cause of ED. This table is a guide for discussion, not a recommendation." },
      {
        type: "cta",
        title: "Not Sure Which Treatment You Need?",
        text: "You do not need to decide before you contact us. Send your case and the clinic can advise which options may be relevant.",
        label: "Send Your Case",
        whatsapp: true,
      },
      { type: "doctor" },
    ],
    faqs: [
      { q: "What causes erectile dysfunction?", a: "Common causes are reduced blood flow, nerve damage, hormonal problems, medicines, psychological factors and surgery in the pelvic area. Many men have more than one cause." },
      { q: "Can ED be a sign of another health problem?", a: "Yes. ED shares risk factors with heart disease and diabetes and can be an early warning sign, so a health review is sensible, particularly if ED is new or getting worse." },
      { q: "Do I need tests for ED?", a: "Not always. The doctor decides after your history and examination. Blood tests are common, and penile Doppler ultrasound is used in selected men to assess blood flow." },
      { q: "Is ED permanent?", a: "It depends on the cause. Some causes can be treated or improved, while others need long-term management. A specialist assessment gives a more realistic picture for your case." },
      { q: "Do I need to know which treatment I want before contacting the clinic?", a: "No. Send your case and the clinic can advise which options may be relevant to you." },
    ],
    sources: ["eau2026", "aua2018"],
    related: ["/erectile-dysfunction-treatment", "/vasculogenic-erectile-dysfunction", "/penile-doppler-ultrasound", "/ed-treatment-options", "/erectile-dysfunction-assessment", "/testosterone-ed", "/post-finasteride-syndrome-ed", "/diabetes-erectile-dysfunction"],
  },
  {
    path: "/erectile-dysfunction-treatment",
    metaTitle: "Erectile Dysfunction Treatment | UZ Clinic Antalya",
    description:
      "Urologist-led ED treatment planning in Antalya: assessment first, then personalised options from established care to regenerative therapies.",
    h1: "Erectile Dysfunction Treatment: A Cause-Based Plan",
    eyebrow: "Treatment pathway",
    kind: "money",
    treatment: "not-sure",
    medical: true,
    evidence: "Individualised",
    answer: {
      q: "How is erectile dysfunction treated?",
      a: "ED treatment starts with finding the likely cause. Lifestyle changes and tablets such as sildenafil or tadalafil are first-line for many men. If they are unsuitable or not enough, a urologist may discuss devices, injections, shockwave therapy, regenerative options or surgery. The most appropriate treatment depends on the underlying cause.",
    },
    lead: "At UZ Clinic Antalya, Dr. Niyazi Umut Özdemir, a urological surgeon and erectile dysfunction specialist, assesses your case first and then explains which options may be relevant to you.",
    takeaways: [
      "Assessment comes before treatment, so the plan fits the cause of your ED.",
      "Established treatments are discussed first. Emerging and experimental options are clearly labelled.",
      "International patients can start with a remote review of their case.",
    ],
    ctaLabel: "Request a Confidential ED Assessment",
    modified: DATE,
    priority: 0.95,
    schema: { condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "steps",
        heading: "From enquiry to treatment plan",
        id: "pathway",
        steps: ASSESS_STEPS,
      },
      {
        type: "cards",
        heading: "Treatments the clinic may discuss",
        id: "treatments",
        intro: "Which of these is relevant depends on your assessment. " + NO_GUARANTEE,
        cols: 2,
        cards: [
          { title: "P-Shot (PRP)", text: "Experimental. Platelet-rich plasma from your own blood is injected into penile tissue.", href: "/p-shot" },
          { title: "Shockwave therapy (EdSWT)", text: "Emerging. Non-invasive sessions, mainly for vasculogenic ED.", href: "/shockwave-therapy-ed" },
          { title: "Stem cell therapy", text: "Experimental. Cell-based preparations injected into penile tissue.", href: "/stem-cell-therapy-erectile-dysfunction" },
          { title: "Exosome therapy", text: "Experimental. Investigational, with very limited human evidence.", href: "/exosome-therapy-erectile-dysfunction" },
          { title: "Penile rehabilitation", text: "An individual plan, for example after prostate surgery.", href: "/penile-rehabilitation" },
          { title: "Established options", text: "Lifestyle changes, PDE5 tablets, injections, vacuum devices and implants, discussed when appropriate.", href: "/ed-treatment-options" },
        ],
      },
      {
        type: "callout",
        tone: "evidence",
        title: "Established, emerging and experimental",
        text: "PDE5 tablets, injections, vacuum devices and implants are established ED treatments. Shockwave therapy is emerging, with a weak guideline recommendation for selected men. PRP, stem cells and exosomes remain experimental or investigational for ED. " + EAU_PRP + " You will receive informed-consent information before any treatment.",
      },
      { type: "cta", title: "Check Treatment Options for Your Case", text: "Tell us about your ED and what you have tried. The clinic can advise what may be relevant.", label: "Check Treatment Options" },
      { type: "checker" },
      { type: "comparison", heading: "Compare the main ED treatments" },
      { type: "cta", title: "Ask the Urologist", text: "Questions about your results, medicines or previous treatments? Send them before you travel.", label: "Ask the Urologist", whatsapp: true },
      { type: "international" },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Which ED treatment is best?", a: "There is no single best treatment. The most appropriate option depends on the cause of ED, your health, your medicines and your preferences." },
      { q: "Do I need to stop my tablets first?", a: "Do not stop or change prescribed medicines because of a website. The doctor will advise at assessment." },
      { q: "Can I be assessed before I travel?", a: "Yes. You can send your case first. Some tests or an in-person examination are still needed before treatment is planned." },
      { q: "Is treatment guaranteed to work?", a: NO_GUARANTEE },
    ],
    sources: ["eau2026", "aua2018"],
    related: ["/erectile-dysfunction", "/ed-treatment-options", "/erectile-dysfunction-treatment-turkey", "/erectile-dysfunction-assessment", "/dr-niyazi-umut-ozdemir"],
  },
  {
    path: "/ed-treatment-options",
    metaTitle: "ED Treatment Options Compared | UZ Clinic Antalya",
    description:
      "Compare P-Shot, shockwave, stem cell, exosome, tablets, injections and implants: candidate, sessions, recovery and how each is meant to work.",
    h1: "ED Treatment Options Compared",
    eyebrow: "Comparison",
    kind: "comparison",
    treatment: "not-sure",
    medical: true,
    evidence: "Mixed",
    answer: {
      q: "What are the treatment options for erectile dysfunction?",
      a: "ED options range from lifestyle changes and PDE5 tablets to injections, vacuum devices, shockwave therapy, regenerative therapies such as PRP, stem cells and exosomes, and penile implants. They differ in evidence, invasiveness and the type of ED they suit. The most appropriate treatment depends on the underlying cause of ED.",
    },
    takeaways: [
      "Established treatments have the strongest evidence; regenerative therapies are still being studied.",
      "The most appropriate treatment depends on the cause, which is why assessment comes first.",
      "Treatments can sometimes be combined, according to the doctor's advice.",
    ],
    ctaLabel: "Check Treatment Options",
    modified: DATE,
    priority: 0.9,
    blocks: [
      { type: "comparison", heading: "Treatment comparison", intro: "A guide for discussion with your urologist. It is not a recommendation or a ranking." },
      {
        type: "text",
        heading: "How the evidence differs",
        id: "evidence",
        bullets: [
          "Established: lifestyle and cardiovascular risk management, PDE5 inhibitors, vacuum erection devices, intracavernosal injections and penile implants.",
          "Emerging: low-intensity shockwave therapy, with a weak EAU recommendation for selected men with vasculogenic ED.",
          "Experimental or investigational: PRP (P-Shot), stem cells and exosomes. " + EAU_PRP,
        ],
      },
      { type: "cta", title: "Which Option May Fit Your ED Type?", text: "Send your case and the clinic can advise which options may be relevant.", label: "Check Which Options Fit My Case" },
      {
        type: "cards",
        heading: "Choosing between options: questions that matter",
        id: "choosing",
        cols: 2,
        cards: [
          { title: "What is the cause of my ED?", text: "Blood flow, nerves, hormones, medicines and psychological factors each point to different options." },
          { title: "What have I already tried?", text: "Correct tablet use, dose and timing matter before concluding that a medicine has failed." },
          { title: "What is my general health?", text: "Heart disease, diabetes, blood thinners and previous surgery can change what is suitable." },
          { title: "What are the evidence and risks?", text: "Ask for the evidence level, risks and alternatives for any option, in writing." },
        ],
      },
      { type: "treatment-nav", heading: "Learn about each treatment" },
      { type: "cta", title: "Speak to the Clinic", text: "Ask the clinic about the treatments that interest you, with no obligation.", label: "Speak to the Clinic", whatsapp: true },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Is there a universal best ED treatment?", a: "No. The most appropriate treatment depends on the underlying cause of ED and on the individual patient." },
      { q: "Are regenerative therapies proven for ED?", a: "No. PRP, stem cells and exosomes are experimental or investigational for ED, and evidence is limited or mixed." },
      { q: "Can treatments be combined?", a: "Sometimes. A doctor may combine options, for example medication with another therapy, after assessment. Evidence for specific combinations is limited." },
    ],
    sources: ["eau2026", "aua2018"],
    related: ["/erectile-dysfunction-treatment", "/p-shot-vs-shockwave", "/p-shot-vs-stem-cell", "/shockwave-vs-stem-cell", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/erectile-dysfunction-treatment-turkey",
    metaTitle: "Erectile Dysfunction Treatment Turkey | UZ Clinic Antalya",
    description:
      "Considering ED treatment in Turkey? How to assess a provider, what to send before travelling and how UZ Clinic Antalya handles international patients.",
    h1: "Erectile Dysfunction Treatment in Turkey",
    eyebrow: "International patients",
    kind: "money",
    treatment: "not-sure",
    medical: true,
    evidence: "Individualised",
    answer: {
      q: "Can I have erectile dysfunction treatment in Turkey?",
      a: "Yes. Men travel to Turkey for ED assessment and treatment. The medical question comes first: you need a diagnosis-led plan from a qualified urologist, clear information about the evidence and risks, and a follow-up plan. UZ Clinic Antalya starts with a remote review of your case before you decide to travel.",
    },
    lead: "UZ Clinic Antalya is a male sexual health clinic in Turkey led by a urologist. International patients can find out which ED specialist-led options may be relevant before they travel.",
    takeaways: [
      "Choose the physician and the plan first, then the travel.",
      "Ask who treats you, what exactly is offered, the evidence and the aftercare.",
      "You can send your case for review before booking any travel.",
    ],
    ctaLabel: "Request a Confidential ED Assessment",
    modified: DATE,
    priority: 0.9,
    blocks: [
      {
        type: "cards",
        heading: "What to check before choosing an ED specialist in Turkey",
        id: "provider-checks",
        cols: 2,
        cards: [
          { title: "Who is the treating doctor?", text: "Ask for the name, specialty and qualifications. At UZ Clinic Antalya the treating specialist is a urological surgeon, Dr. Niyazi Umut Özdemir.", href: "/dr-niyazi-umut-ozdemir" },
          { title: "Is the plan based on a diagnosis?", text: "A good plan follows the cause of ED, not a standard package." },
          { title: "Is the evidence explained honestly?", text: "You should hear which treatments are established and which are experimental, including the limits of the evidence." },
          { title: "What happens after you go home?", text: "Ask about follow-up, who you can contact and what to do if something goes wrong." },
        ],
      },
      { type: "cta", title: "Send Your Case Before You Travel", text: "The clinic can review your situation remotely and tell you which next steps make sense.", label: "Send Your Case" },
      { type: "international" },
      {
        type: "text",
        heading: "Treatments the clinic may discuss",
        id: "treatments",
        bullets: [
          "P-Shot (PRP): experimental for ED. See the P-Shot guide for the evidence and procedure.",
          "Shockwave therapy (EdSWT): mainly for vasculogenic ED, using a 12-session protocol.",
          "Stem cell and exosome therapy: experimental or investigational, considered only after evaluation.",
          "Established options and penile rehabilitation where appropriate.",
        ],
      },
      { type: "treatment-nav", heading: "Explore treatments available for assessment" },
      { type: "cta", title: "Ask the Urologist", text: "Have questions about travelling for treatment? Ask before you book anything.", label: "Ask the Urologist", whatsapp: true },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Can I be assessed before I travel to Turkey?", a: "Yes. Send your history, medicines and any reports or Doppler results. The clinic can review them and advise on next steps. An in-person assessment is still required before treatment." },
      { q: "How long should I plan to stay?", a: "It depends on the plan. For example, the shockwave protocol is a course of sessions over weeks. The coordinator explains timing after reviewing your case." },
      { q: "Is treatment in Turkey equivalent to treatment at home?", a: "Quality depends on the doctor, the facility and the plan, not on the country. Ask for the doctor's qualifications, the written treatment plan, the evidence and the follow-up arrangements." },
    ],
    sources: ["eau2026"],
    related: ["/erectile-dysfunction-treatment-antalya", "/international-patients", "/erectile-dysfunction-assessment", "/p-shot-turkey", "/dr-niyazi-umut-ozdemir", "/erectile-dysfunction-treatment"],
  },
  {
    path: "/erectile-dysfunction-treatment-antalya",
    metaTitle: "ED Treatment in Antalya | Dr. Niyazi Umut Özdemir",
    description:
      "Visit a urologist in Antalya for erectile dysfunction assessment and treatment planning. What the visit involves and how to start with a remote review.",
    h1: "Erectile Dysfunction Treatment in Antalya",
    eyebrow: "Visiting the clinic",
    kind: "money",
    treatment: "not-sure",
    medical: true,
    evidence: "Individualised",
    answer: {
      q: "Where can I get specialist ED treatment in Antalya?",
      a: "UZ Clinic Antalya is a urologist-led service for male sexual health and penile rehabilitation in Antalya, Turkey. Dr. Niyazi Umut Özdemir, a urological surgeon, assesses your ED and explains which treatment options may be relevant. You can send your case for review before you visit.",
    },
    takeaways: [
      "A physician-led clinic focused on male sexual health and penile rehabilitation.",
      "Assessment first: history, examination and tests when useful.",
      "Local and international patients are welcome to send their case.",
    ],
    ctaLabel: "Check If You're Suitable",
    modified: DATE,
    priority: 0.85,
    blocks: [
      {
        type: "steps",
        heading: "What a visit to the clinic involves",
        id: "visit",
        steps: [
          { title: "Remote review (optional)", text: "Send your case first so the clinic can plan the visit and ask for any reports in advance." },
          { title: "Consultation", text: "You meet the urologist, discuss your symptoms in private and have an examination." },
          { title: "Tests when useful", text: "Blood tests or penile Doppler ultrasound may be used to find the likely cause." },
          { title: "Plan and consent", text: "If treatment is appropriate, the doctor explains the options, evidence, risks and alternatives before you decide." },
        ],
      },
      {
        type: "text",
        heading: "What to bring or send",
        id: "bring",
        bullets: [
          "A list of your current medicines and any ED treatments you have tried.",
          "Recent blood tests, a heart or diabetes review, or Doppler ultrasound results if you have them.",
          "Details of any pelvic or prostate surgery or radiotherapy.",
          "Your questions, written down.",
        ],
      },
      { type: "cta", title: "Send Your Case to the Clinic", text: "Share your history confidentially. A patient coordinator will contact you.", label: "Send Your Case" },
      { type: "doctor" },
      { type: "location" },
      { type: "international" },
      { type: "treatment-nav", heading: "Treatments you can ask about" },
      { type: "cta", title: "Speak to the Clinic", text: "Prefer to chat? Message the clinic on WhatsApp.", label: "Speak to the Clinic", whatsapp: true },
    ],
    faqs: [
      { q: "Do I need a referral?", a: "You can contact the clinic directly. Sending previous reports helps the doctor review your case." },
      { q: "Is the first contact confidential?", a: "Yes. Enquiries are handled confidentially, and you do not need to call." },
      { q: "Can I begin treatment on my first visit?", a: "Treatment is planned after assessment. Whether anything can be done on the same trip depends on your case and is explained by the clinic." },
    ],
    sources: ["eau2026"],
    related: ["/erectile-dysfunction-treatment-turkey", "/international-patients", "/dr-niyazi-umut-ozdemir", "/erectile-dysfunction-assessment", "/p-shot-antalya", "/shockwave-therapy-ed", "/price"],
  },
];
