import { DATE, EAU_PRP, NO_GUARANTEE } from "../shared";
import type { PageDef } from "../types";

const prpSources = ["eau2026", "aua2018", "panunzio2024", "masterson2023", "poulios2021"];

export const pshotPages: PageDef[] = [
  {
    path: "/p-shot",
    metaTitle: "P-Shot PRP for Erectile Dysfunction | UZ Clinic Antalya",
    description:
      "What the P-Shot is, how PRP is prepared and injected, who may be suitable, risks and what the evidence shows. Check suitability with a urologist.",
    h1: "P-Shot PRP Treatment for Erectile Dysfunction",
    eyebrow: "Treatment guide",
    kind: "money",
    treatment: "p-shot",
    medical: true,
    evidence: "Experimental",
    answer: {
      q: "What is P-Shot?",
      a: "P-Shot is a penile PRP procedure in which platelet-rich plasma prepared from the patient's own blood is injected into penile tissue. It is used by some clinics as a regenerative approach for selected men with erectile dysfunction. It is considered experimental, and suitability and expected benefit vary between patients.",
    },
    lead: "This guide explains the procedure in plain language, who it may or may not suit, and what research does and does not show.",
    takeaways: [
      "Your own blood is processed to concentrate platelets, then injected after numbing. It is an outpatient procedure.",
      "Evidence is mixed. " + EAU_PRP,
      "A specialist assessment decides whether it is relevant for you, and established options are discussed first.",
    ],
    ctaLabel: "Am I Suitable for P-Shot?",
    modified: DATE,
    priority: 1,
    schema: { therapy: "P-Shot (platelet-rich plasma injection)", condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "text",
        heading: "What is P-Shot?",
        id: "what-is-p-shot",
        paragraphs: [
          "PRP stands for platelet-rich plasma. It is made from a sample of your own blood. Platelets release growth factors, which is why PRP is being studied in several areas of medicine.",
          "In the P-Shot, the PRP is injected into penile tissue. The idea is that it may support tissue repair and blood flow. This is a proposed mechanism. It has not been proven to restore erections in people.",
        ],
      },
      {
        type: "steps",
        heading: "How is PRP prepared and the P-Shot performed?",
        id: "procedure",
        intro: "The exact protocol is explained by the clinic at assessment. The usual stages are:",
        steps: [
          { title: "Assessment and consent", text: "The urologist reviews your history and examines you, and explains the evidence, risks and alternatives. You sign written consent before treatment." },
          { title: "Blood sample", text: "A small amount of blood is taken from your arm using a sterile technique." },
          { title: "PRP preparation", text: "The blood is spun in a centrifuge. This separates the plasma and concentrates the platelets into platelet-rich plasma." },
          { title: "Numbing", text: "Local anaesthetic or numbing cream is used so the injection is more comfortable." },
          { title: "Injection", text: "The PRP is injected into penile tissue by the doctor. It is an outpatient procedure, so you go home the same day." },
          { title: "Aftercare", text: "You receive written aftercare instructions, warning signs and a contact for questions." },
        ],
      },
      { type: "cta", title: "See Whether P-Shot Fits Your Case", text: "Tell us about your ED and what you have tried. The urologist can advise whether PRP may be relevant.", label: "Am I Suitable for P-Shot?" },
      {
        type: "cards",
        heading: "Who may be suitable, and who may not",
        id: "suitability",
        cols: 2,
        cards: [
          { title: "May be considered", text: "Men with organic ED after assessment who understand that the treatment is experimental, have discussed established options and want to explore a regenerative approach." },
          { title: "Depends on the cause", text: "Benefit may vary with the cause of ED. Severe nerve damage or advanced vascular disease may limit any effect. The doctor explains this at assessment." },
          { title: "May not be suitable", text: "Active infection or skin lesions, bleeding disorders or blood-thinning medicines, low platelet count, current cancer treatment or a weakened immune system, or allergy to local anaesthetic." },
          { title: "Needs review first", text: "Penile pain, curvature, a lump or suspected Peyronie's disease, and untreated heart disease, diabetes or hormonal problems should be assessed before any ED procedure." },
        ],
      },
      {
        type: "text",
        heading: "P-Shot for erectile dysfunction: what the research shows",
        id: "evidence",
        paragraphs: [
          "Some randomised trials report better erectile-function questionnaire scores after PRP than after placebo. A 2023 randomised placebo-controlled trial found no efficacy difference and no change in penile Doppler measures over six months. Reviews describe encouraging signals but also big differences in preparation, dose and study quality.",
          EAU_PRP + " For that reason, the clinic discusses PRP as an experimental option and only after assessment.",
        ],
      },
      {
        type: "text",
        heading: "P-Shot and erection quality",
        id: "erection-quality",
        paragraphs: [
          "Men often ask whether PRP can improve hardness or help them keep an erection. In studies, such outcomes are measured with questionnaires and sometimes Doppler ultrasound. Results differ between studies. Suitability and expected benefit vary between patients and depend on the underlying cause.",
        ],
      },
      { type: "comparison", heading: "P-Shot compared with other options", highlight: ["p-shot", "shockwave", "stem-cell"] },
      {
        type: "cards",
        heading: "P-Shot vs other regenerative approaches",
        id: "vs",
        cols: 2,
        cards: [
          { title: "P-Shot vs Shockwave Therapy", text: "PRP is an injection of platelet concentrate. Shockwave is a non-invasive course of sessions, mainly for vasculogenic ED.", href: "/p-shot-vs-shockwave" },
          { title: "P-Shot vs Stem Cell Therapy", text: "PRP uses platelets from your blood. Stem-cell approaches use cells and are less standardised.", href: "/p-shot-vs-stem-cell" },
        ],
      },
      { type: "cta", title: "Compare Your Options With the Urologist", text: "Not sure whether PRP, shockwave or another option fits your ED type? Send your case.", label: "Check Treatment Options", whatsapp: true },
      {
        type: "text",
        heading: "Recovery and what to expect afterwards",
        id: "recovery",
        paragraphs: [
          "Most men go home the same day. Some tenderness, bruising or swelling in the first days is common. The doctor gives specific instructions on activity, including when to resume sexual activity.",
        ],
      },
      {
        type: "cards",
        heading: "Possible side effects",
        id: "side-effects",
        cols: 2,
        intro: "Reported adverse events in studies have generally been minor, but trials are too small to define uncommon risks. Using your own blood avoids rejection but does not make an injection risk-free.",
        cards: [
          { title: "Common", text: "Temporary pain, tenderness, bruising, redness or swelling at the injection site." },
          { title: "Bleeding", text: "Bleeding or a haematoma can occur, and risk may be higher with blood thinners or bleeding disorders." },
          { title: "Infection", text: "Any injection can cause infection if sterile technique is not followed." },
          { title: "Seek urgent help", text: "Fever, spreading redness, pus, severe or worsening pain, heavy bleeding, difficulty passing urine or an erection lasting more than four hours." },
        ],
      },
      {
        type: "text",
        heading: "When might I notice a change?",
        id: "timeline",
        paragraphs: [
          "In published studies, outcomes were usually assessed over weeks to months, for example up to six months. No fixed timeline can be promised, and some men notice no change. The clinic explains how it measures progress and what follow-up it offers.",
        ],
      },
      { type: "stories", heading: "P-Shot patient stories" },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Is the P-Shot proven to treat erectile dysfunction?", a: "No. Some trials report improvement, while others found no difference from placebo. " + EAU_PRP },
      { q: "Does the P-Shot hurt?", a: "Numbing is used before the injection. Many men describe mild discomfort, but experiences differ." },
      { q: "Is the P-Shot permanent?", a: "No permanent effect can be promised. If there is a benefit, how long it lasts is uncertain and varies between patients." },
      { q: "Is the P-Shot safe?", a: "Reported side effects have mostly been minor, but studies are small and long-term data are limited. The doctor explains the risks and who should not have it." },
      { q: "Does the P-Shot increase penis size?", a: "No. P-Shot is not a penile-enlargement treatment and the clinic does not claim it enlarges the penis." },
      { q: "Can I have P-Shot together with other treatments?", a: "Sometimes the doctor may discuss combinations, but evidence is limited. Treatment is decided after assessment." },
      { q: "What is the difference between P-Shot and PRP for ED?", a: "P-Shot is a brand-style name for penile PRP injection. The medical term is intracavernosal platelet-rich plasma injection." },
    ],
    sources: prpSources,
    related: ["/prp-for-erectile-dysfunction", "/p-shot-turkey", "/p-shot-antalya", "/shockwave-therapy-ed", "/stem-cell-therapy-erectile-dysfunction", "/exosome-therapy-erectile-dysfunction", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/p-shot-turkey",
    metaTitle: "P-Shot Turkey: PRP for Erectile Dysfunction | UZ Clinic",
    description:
      "P-Shot in Turkey for international patients: remote case review, what to send, travel planning and what to ask any provider. Confidential assessment.",
    h1: "P-Shot in Turkey: Information for International Patients",
    eyebrow: "P-Shot abroad",
    kind: "money",
    treatment: "p-shot",
    medical: true,
    evidence: "Experimental",
    answer: {
      q: "Can I have a P-Shot in Turkey?",
      a: "Yes, P-Shot (penile PRP) is offered in Turkey, including at UZ Clinic Antalya, after assessment by a urologist. Because PRP for ED is experimental, you should see the evidence, risks and alternatives in writing, and plan follow-up before you travel. You can send your case for remote review first.",
    },
    takeaways: [
      "Start with a remote case review, then confirm the plan in person.",
      "Ask who treats you, what is injected, what the evidence is and how follow-up works.",
      "Suitability is decided by the doctor, not by price or package.",
    ],
    ctaLabel: "Am I Suitable for P-Shot?",
    modified: DATE,
    priority: 0.9,
    schema: { therapy: "P-Shot (platelet-rich plasma injection)", condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "text",
        heading: "Why men look at P-Shot in Turkey",
        id: "why",
        paragraphs: [
          "Men often search abroad for a urologist-led service, shorter waiting times or a different price. Whatever the reason, the same medical standards should apply: a proper assessment, honest information about the evidence, written consent and follow-up.",
        ],
      },
      {
        type: "text",
        heading: "What to send before you travel",
        id: "send",
        bullets: [
          "Your age, how long you have had ED and what the main problem is.",
          "Medicines and any ED treatments tried, including tablets and how you used them.",
          "Medical history: diabetes, blood pressure, heart disease, prostate or pelvic surgery, Peyronie's disease.",
          "Recent blood tests or a penile Doppler ultrasound result, if you have them.",
        ],
      },
      { type: "cta", title: "Send Your Case for Review", text: "The clinic can tell you whether P-Shot may be relevant before you plan any travel.", label: "Send Your Case for P-Shot Review" },
      { type: "international" },
      {
        type: "callout",
        tone: "evidence",
        title: "Evidence in brief",
        text: "Trials of PRP for ED report mixed results, and protocols are not standardised. " + EAU_PRP + " " + NO_GUARANTEE,
      },
      {
        type: "text",
        heading: "Questions to ask any P-Shot provider",
        id: "questions",
        bullets: [
          "Who performs the injection, and what are their qualifications?",
          "Why is PRP proposed for my type of ED, and what established options were considered?",
          "What preparation system and protocol are used, and how many sessions are planned?",
          "What are the risks, and who do I contact after I go home?",
          "What is included in the price, and what is not?",
        ],
      },
      { type: "treatment-nav", heading: "Other treatments you can ask about", exclude: ["p-shot"] },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Do I have to travel before the clinic can advise me?", a: "No. You can send your case and the clinic can advise on whether P-Shot may be relevant, though an in-person assessment is needed before treatment." },
      { q: "How long does a P-Shot trip take?", a: "The procedure itself is outpatient. The coordinator explains how long to plan for after reviewing your case." },
      { q: "How much does a P-Shot cost in Turkey?", a: "See the price page for the advertised fee. The final plan and what it includes are confirmed after assessment." },
    ],
    sources: prpSources,
    related: ["/p-shot", "/p-shot-antalya", "/price", "/international-patients", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/p-shot-antalya",
    metaTitle: "P-Shot Antalya | PRP ED Treatment | Dr. Niyazi Umut Özdemir",
    description:
      "P-Shot at UZ Clinic Antalya: what the appointment involves, how Dr. Niyazi Umut Özdemir assesses suitability and how to send your case first.",
    h1: "P-Shot at UZ Clinic Antalya",
    eyebrow: "Treatment at the clinic",
    kind: "money",
    treatment: "p-shot",
    medical: true,
    evidence: "Experimental",
    answer: {
      q: "How does a P-Shot appointment work at UZ Clinic Antalya?",
      a: "After a case review and an in-person assessment by the urologist, suitable patients may be offered a P-Shot. The visit covers consent, a blood sample, PRP preparation, numbing and injection as an outpatient procedure, followed by aftercare instructions. PRP for ED is experimental, so the doctor explains the evidence and alternatives first.",
    },
    ctaLabel: "Am I Suitable for P-Shot?",
    modified: DATE,
    priority: 0.8,
    schema: { therapy: "P-Shot (platelet-rich plasma injection)", condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "steps",
        heading: "Your P-Shot appointment, step by step",
        id: "appointment",
        steps: [
          { title: "Private consultation", text: "You discuss your ED with the urologist, who reviews your history, medicines and previous treatments." },
          { title: "Examination and tests", text: "An examination and any needed tests, such as blood tests or Doppler ultrasound, show whether PRP is a sensible option." },
          { title: "Informed consent", text: "The doctor explains the evidence, the risks and the alternatives, and you decide whether to go ahead." },
          { title: "Blood draw and PRP preparation", text: "Your own blood is taken and processed in a centrifuge to prepare platelet-rich plasma." },
          { title: "Numbing and injection", text: "After local anaesthetic or numbing, the PRP is injected by the doctor." },
          { title: "Aftercare and follow-up", text: "You receive written instructions and a contact for questions, plus the follow-up plan." },
        ],
      },
      { type: "cta", title: "Check If P-Shot Is Right for You", text: "Send your case and the urologist can advise before you visit.", label: "Check If P-Shot Is Right for You" },
      { type: "doctor" },
      {
        type: "callout",
        tone: "evidence",
        title: "What we tell every patient",
        text: "PRP for ED is experimental. " + EAU_PRP + " " + NO_GUARANTEE + " P-Shot is not a penile-enlargement treatment.",
      },
      { type: "location" },
      { type: "international" },
      { type: "stories", heading: "P-Shot patient stories" },
      { type: "cta", title: "Ask the Urologist", text: "Questions before you decide? Message the clinic on WhatsApp.", label: "Ask the Urologist", whatsapp: true },
    ],
    faqs: [
      { q: "Can I have a P-Shot on the day I arrive?", a: "Treatment follows assessment. Whether it can happen on the same trip depends on your case, and the coordinator explains the plan in advance." },
      { q: "Who performs the P-Shot?", a: "Dr. Niyazi Umut Özdemir, the clinic's urological surgeon, leads assessment and treatment planning." },
      { q: "Where is the clinic?", a: "UZ Clinic Antalya is at Fener Mah., Bülent Ecevit Blv., Kanyon Plaza No:23, Kat:4, Daire:7, 07160 Muratpaşa / Antalya, Turkey. Directions are on the contact section of this page." },
    ],
    sources: prpSources,
    related: ["/p-shot", "/p-shot-turkey", "/dr-niyazi-umut-ozdemir", "/erectile-dysfunction-treatment-antalya", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/prp-for-erectile-dysfunction",
    metaTitle: "PRP for Erectile Dysfunction: What the Evidence Shows",
    description:
      "Can PRP help erectile dysfunction? A plain-English review of the trials, the EAU guideline position, limits of the evidence and how to decide.",
    h1: "PRP for Erectile Dysfunction: What the Evidence Shows",
    eyebrow: "Evidence review",
    kind: "money",
    treatment: "p-shot",
    medical: true,
    evidence: "Experimental",
    answer: {
      q: "Can PRP help erectile dysfunction?",
      a: "Some studies report improved erectile function after penile PRP injections, but results are mixed and protocols vary. A 2023 placebo-controlled trial found no benefit over placebo. The 2026 EAU guideline says PRP for ED should be used only in a clinical-trial setting, so any use outside trials is experimental and should follow full consent.",
    },
    takeaways: [
      "Evidence is mixed, with small studies and different protocols.",
      "Guidelines do not currently recommend PRP for routine ED care.",
      "A specialist assessment shows whether PRP is even relevant for your type of ED.",
    ],
    ctaLabel: "Check If PRP May Be Relevant",
    modified: DATE,
    priority: 0.85,
    schema: { therapy: "Platelet-rich plasma (PRP) injection", condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "table",
        heading: "What the research shows",
        id: "research",
        caption: "Summary of the evidence on PRP for ED, as described in the cited guideline and studies.",
        headers: ["Source", "What it reports"],
        rows: [
          ["2026 EAU guideline", "PRP for ED should be used only in a clinical-trial setting."],
          ["Randomised trials (for example Poulios 2021)", "Some report improved erectile-function scores compared with placebo."],
          ["2023 randomised placebo-controlled trial (Masterson)", "No significant difference from placebo and no Doppler improvement through six months."],
          ["Systematic review and meta-analysis (Panunzio 2024)", "Promising signals, with large variation in dose, preparation and study quality."],
        ],
      },
      {
        type: "text",
        heading: "Why results differ",
        id: "limits",
        bullets: [
          "Studies are often small and short.",
          "PRP is prepared in different ways, so platelet concentration and activation vary.",
          "Men studied differ in age, ED cause and severity.",
          "Best candidates, number of sessions and long-term benefit are still unknown.",
        ],
      },
      { type: "cta", title: "Find Out If PRP May Be Relevant to You", text: "The urologist can say whether your type of ED is one in which PRP might be discussed.", label: "Check If PRP May Be Relevant" },
      {
        type: "callout",
        tone: "caution",
        title: "What good consent should include",
        text: "That PRP for ED is experimental, that results are not guaranteed, that established alternatives have been discussed, and a written explanation of the protocol, risks, follow-up and cost. An FDA-cleared centrifuge does not mean PRP for ED is FDA-approved.",
      },
      { type: "treatment-nav", heading: "Compare with other options", exclude: ["p-shot"] },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Is PRP approved for erectile dysfunction?", a: "PRP for ED is not part of standard guideline care. The EAU says it should be used only in clinical trials." },
      { q: "Is PRP better than Viagra?", a: "No evidence shows that. PDE5 inhibitors have established evidence and are first-line for many men. PRP is experimental." },
      { q: "Who might still consider PRP?", a: "Some well-informed men with organic ED, after discussing established options, may choose to explore it. The doctor decides after assessment." },
    ],
    sources: prpSources,
    related: ["/p-shot", "/p-shot-vs-viagra", "/p-shot-vs-shockwave", "/p-shot-vs-stem-cell", "/erectile-dysfunction-assessment"],
  },
];
