import { DATE, NO_GUARANTEE } from "../shared";
import type { PageDef } from "../types";

const EAU_STEM =
  "The 2026 EAU guideline considers the evidence for stem-cell therapy in ED insufficient for routine clinical use.";

export const regenerativePages: PageDef[] = [
  {
    path: "/stem-cell-therapy-erectile-dysfunction",
    metaTitle: "Stem Cell Therapy for Erectile Dysfunction | UZ Clinic",
    description:
      "What stem cell therapy for ED is, why it is being studied, who may be considered, the limits of the evidence and how the clinic assesses candidates.",
    h1: "Stem Cell Therapy for Erectile Dysfunction",
    eyebrow: "Regenerative treatment",
    kind: "money",
    treatment: "stem-cell",
    medical: true,
    evidence: "Experimental",
    answer: {
      q: "Can stem cells treat erectile dysfunction?",
      a: "Stem cells are being studied as a regenerative approach for ED, but they are not an established treatment. Studies so far are small and varied, and no success rate can be promised. " + EAU_STEM + " Any use should follow specialist assessment and detailed informed consent.",
    },
    lead: "This page explains the idea behind stem-cell therapy, what is known and unknown, and how the clinic decides whether to discuss it with you.",
    takeaways: [
      "Experimental. It is not a standard ED treatment.",
      "Sources, preparation and procedures differ widely between clinics.",
      "The clinic assesses your cause of ED first, and discusses established options before regenerative ones.",
    ],
    ctaLabel: "Check Stem Cell Suitability",
    modified: DATE,
    priority: 0.9,
    schema: { therapy: "Stem cell therapy for erectile dysfunction", condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "text",
        heading: "What are stem cells?",
        id: "what-are-stem-cells",
        paragraphs: [
          "Stem cells are cells that can develop into other cell types and release signalling molecules. In regenerative medicine, researchers study whether they can support the repair of damaged tissue.",
        ],
      },
      {
        type: "text",
        heading: "Why are regenerative approaches studied for ED?",
        id: "why-studied",
        paragraphs: [
          "In many men, ED involves damage to blood vessels, nerves or the smooth muscle in the penis. Tablets treat symptoms but do not repair these tissues. Researchers are therefore testing whether cell-based therapies could support repair.",
          "The proposed mechanisms include supporting blood-vessel growth, protecting tissue and releasing growth factors. These are hypotheses. Human evidence is still limited.",
        ],
      },
      { type: "cta", title: "Ask Whether Stem Cell Therapy Could Apply to You", text: "Send your case. The urologist can say whether it is worth discussing, and which established options come first.", label: "Check Stem Cell Suitability" },
      {
        type: "cards",
        heading: "Who may be considered, and who may not",
        id: "suitability",
        cols: 2,
        cards: [
          { title: "May be considered", text: "Selected men with organic ED, after assessment, for whom established options were unsuitable or ineffective, who understand the treatment is experimental." },
          { title: "May not be suitable", text: "Men with active infection, some blood disorders, current cancer or an unassessed cause of ED, among other reasons. The doctor screens for these." },
          { title: "Needs review first", text: "Men with untreated heart disease, diabetes or hormonal problems, or recent pelvic surgery, should be assessed before any regenerative treatment." },
          { title: "Not a priority", text: "ED mainly due to psychological factors or to a medicine usually needs a different approach first." },
        ],
      },
      {
        type: "table",
        heading: "Stem cells, PRP and exosomes: what is the difference?",
        id: "difference",
        caption: "How the main regenerative approaches differ in concept. All three are experimental or investigational for ED.",
        headers: ["", "PRP (P-Shot)", "Stem cells", "Exosomes"],
        rows: [
          ["What it is", "Concentrated platelets and plasma from your blood", "Cells or a cell-based preparation", "Tiny vesicles released by cells"],
          ["Proposed role", "Growth-factor signalling", "Cell signalling and support of repair", "Messenger signalling between cells"],
          ["Standardisation", "Preparation varies between systems", "Sources and methods vary widely", "Products and methods vary; human data very limited"],
          ["ED status", "Experimental; EAU: clinical trials only", "Experimental; evidence insufficient", "Investigational; very limited human evidence"],
        ],
      },
      {
        type: "steps",
        heading: "Assessment, procedure and recovery",
        id: "process",
        intro: "Details depend on the protocol. The clinic explains its exact source, preparation and procedure at assessment, with written consent.",
        steps: [
          { title: "Assessment", text: "History, examination and, when useful, penile Doppler and blood tests." },
          { title: "Discussion of options", text: "Established treatments first, then whether a regenerative approach is appropriate." },
          { title: "Informed consent", text: "Written information on the product, procedure, risks, evidence and alternatives." },
          { title: "Procedure and aftercare", text: "If offered, the procedure is explained step by step, with written aftercare. Recovery instructions come from the doctor." },
        ],
      },
      {
        type: "callout",
        tone: "evidence",
        title: "Evidence and limitations",
        text: EAU_STEM + " Studies are small and heterogeneous, with few placebo-controlled trials. No success rate is claimed here. " + NO_GUARANTEE,
      },
      { type: "comparison", heading: "How stem cells compare with other treatments", highlight: ["stem-cell", "p-shot", "exosome"] },
      { type: "cta", title: "Speak to the Clinic About Regenerative Options", text: "Ask which regenerative options, if any, may be relevant to your case.", label: "Ask the Urologist", whatsapp: true },
      { type: "stories", heading: "Patient experiences" },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Are stem cells proven for erectile dysfunction?", a: "No. Evidence is limited and the guideline considers it insufficient for routine use. No success rate can responsibly be promised." },
      { q: "What is the difference between stem cell therapy and PRP?", a: "PRP is concentrated platelets from your blood. Stem-cell approaches use cells or cell-based preparations. Both are experimental for ED." },
      { q: "Is stem cell therapy safe?", a: "Risks depend on the source and the procedure. The doctor explains them in writing. Long-term safety data in ED are limited." },
      { q: "Do I need to try tablets first?", a: "Established options are usually discussed first. The doctor decides what is appropriate for your case." },
      { q: "Can stem cell therapy enlarge the penis?", a: "No. The clinic does not claim that it does." },
    ],
    sources: ["eau2026", "aua2018", "clinicalTrial"],
    related: ["/stem-cell-treatment-ed-turkey", "/p-shot-vs-stem-cell", "/shockwave-vs-stem-cell", "/exosome-therapy-erectile-dysfunction", "/ed-treatment-options", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/stem-cell-treatment-ed-turkey",
    metaTitle: "Stem Cell Treatment for ED in Turkey | UZ Clinic Antalya",
    description:
      "Considering stem cell treatment for ED in Turkey? What to ask any provider, how remote review works and why assessment comes first.",
    h1: "Stem Cell Treatment for ED in Turkey: What to Know Before You Travel",
    eyebrow: "Regenerative treatment abroad",
    kind: "money",
    treatment: "stem-cell",
    medical: true,
    evidence: "Experimental",
    answer: {
      q: "Is stem cell treatment for erectile dysfunction available in Turkey?",
      a: "Some clinics in Turkey offer stem-cell or cell-based treatments for ED. Because the approach is experimental, the key questions are about the doctor, the product, the consent and the evidence, not the destination. At UZ Clinic Antalya, a urologist reviews your case first and explains whether any regenerative option is appropriate.",
    },
    ctaLabel: "Check Stem Cell Suitability",
    modified: DATE,
    priority: 0.8,
    schema: { therapy: "Stem cell therapy for erectile dysfunction", condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "text",
        heading: "Questions to ask any provider offering stem cells for ED",
        id: "questions",
        bullets: [
          "What exactly is injected, where does it come from and how is it prepared?",
          "Which published study used the same protocol in men like me?",
          "Is it offered within a registered clinical study?",
          "What are the risks, who treats complications and what is the follow-up plan?",
          "What established options were considered first?",
        ],
      },
      { type: "cta", title: "Send Your Case Before You Travel", text: "The urologist can review your history and tell you whether stem-cell therapy is even worth discussing.", label: "Check Stem Cell Suitability" },
      {
        type: "callout",
        tone: "evidence",
        title: "Experimental treatment",
        text: EAU_STEM + " " + NO_GUARANTEE,
      },
      { type: "international" },
      { type: "treatment-nav", heading: "Other treatments you can ask about", exclude: ["stem-cell"] },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Can I be assessed before travelling?", a: "Yes. Send your case first. An in-person assessment is still needed before any procedure." },
      { q: "Do you promise results?", a: "No. " + NO_GUARANTEE },
    ],
    sources: ["eau2026", "clinicalTrial"],
    related: ["/stem-cell-therapy-erectile-dysfunction", "/international-patients", "/erectile-dysfunction-treatment-turkey", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/exosome-therapy-erectile-dysfunction",
    metaTitle: "Exosome Therapy for Erectile Dysfunction | UZ Clinic Antalya",
    description:
      "What exosomes are, why they are being investigated for ED, how they differ from PRP and stem cells, and the limits of the evidence. Ask about suitability.",
    h1: "Exosome Therapy for Erectile Dysfunction",
    eyebrow: "Investigational treatment",
    kind: "money",
    treatment: "exosome",
    medical: true,
    evidence: "Experimental",
    answer: {
      q: "What is exosome therapy for ED?",
      a: "Exosomes are tiny vesicles released by cells that carry signalling molecules. Researchers are investigating whether exosome-based preparations could support tissue repair, including in erectile dysfunction. Most research is laboratory or animal work, and human evidence is very limited. Any availability is subject to clinical evaluation.",
    },
    lead: "This page is deliberately cautious. It explains the idea, the differences from other regenerative approaches and the limits of what is known.",
    takeaways: [
      "Investigational. Human evidence for ED is very limited.",
      "The clinic does not publish success rates, doses or outcome claims for exosome therapy.",
      "Availability depends on clinical evaluation of your case.",
    ],
    ctaLabel: "Check Exosome Therapy Suitability",
    modified: DATE,
    priority: 0.85,
    schema: { therapy: "Exosome therapy (investigational)", condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "text",
        heading: "What are exosomes?",
        id: "what-are-exosomes",
        paragraphs: [
          "Exosomes are very small extracellular vesicles. Cells release them to communicate with other cells, carrying proteins and genetic material.",
        ],
      },
      {
        type: "text",
        heading: "Why are exosomes investigated in regenerative medicine?",
        id: "why-investigated",
        paragraphs: [
          "Some of the repair effects seen with cell-based therapies may come from the signals cells release rather than from the cells themselves. This has led researchers to study exosome preparations as a cell-free option.",
          "For ED, the idea is that these signals might support blood vessels, nerves or erectile tissue. This remains a research hypothesis.",
        ],
      },
      { type: "cta", title: "Ask Whether Exosome Therapy Is Suitable for Your Case", text: "Send your history. The urologist can say whether this investigational option is relevant, and what comes first.", label: "Ask Whether Exosome Therapy Is Suitable for Your Case" },
      {
        type: "table",
        heading: "PRP, exosomes, stem cells and shockwave: key differences",
        id: "differences",
        caption: "Concept and evidence status for ED, as understood from current guidelines and research.",
        headers: ["Approach", "What it is", "Status for ED"],
        rows: [
          ["PRP", "Concentrated platelets from your own blood", "Experimental; EAU: clinical trials only"],
          ["Exosomes", "Cell-released vesicles", "Investigational; very limited human evidence"],
          ["Stem cells", "Cells or cell-based preparation", "Experimental; evidence insufficient"],
          ["Shockwave", "Low-intensity shockwaves, no injection", "Emerging; weak EAU recommendation for selected men"],
        ],
      },
      {
        type: "cards",
        heading: "Candidate assessment and consultation",
        id: "assessment",
        cols: 2,
        cards: [
          { title: "Assessment first", text: "The urologist identifies the likely cause of your ED and considers established options before any investigational therapy." },
          { title: "Availability", text: "Whether exosome therapy is offered depends on the clinical evaluation of your case." },
          { title: "Informed consent", text: "If offered, you receive written information about the preparation, risks, evidence and alternatives." },
          { title: "No outcome claims", text: "The clinic does not publish success rates or promise results for exosome therapy." },
        ],
      },
      {
        type: "callout",
        tone: "evidence",
        title: "Current evidence limitations",
        text: "Most exosome research for ED is preclinical (laboratory and animal studies). Controlled human data are very limited, and there is no established dose, protocol or approved indication for ED. " + NO_GUARANTEE,
      },
      { type: "cta", title: "Speak to the Clinic", text: "Ask whether any regenerative option makes sense for you.", label: "Ask the Urologist", whatsapp: true },
      { type: "treatment-nav", heading: "Compare with other options", exclude: ["exosome"] },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Is exosome therapy proven for ED?", a: "No. Evidence is mostly preclinical, and human data are very limited." },
      { q: "Is exosome therapy approved for ED?", a: "The clinic does not claim any approved indication for ED. Treatment availability is subject to clinical evaluation." },
      { q: "What is the difference between exosomes and stem cells?", a: "Stem cells are cells. Exosomes are vesicles that cells release. Both are investigated for repair signalling." },
      { q: "How many sessions are needed?", a: "No established protocol exists for ED. If the clinic offers it for your case, the doctor explains the plan." },
    ],
    sources: ["eau2026", "clinicalTrial"],
    related: ["/exosome-therapy-turkey", "/stem-cell-therapy-erectile-dysfunction", "/p-shot", "/ed-treatment-options", "/erectile-dysfunction-assessment"],
  },
  {
    path: "/exosome-therapy-turkey",
    metaTitle: "Exosome Therapy for ED in Turkey | UZ Clinic Antalya",
    description:
      "Exosome therapy for erectile dysfunction in Turkey: what to ask, why availability depends on assessment and how to send your case for review.",
    h1: "Exosome Therapy for ED in Turkey",
    eyebrow: "Investigational treatment abroad",
    kind: "money",
    treatment: "exosome",
    medical: true,
    evidence: "Experimental",
    answer: {
      q: "Is exosome therapy for erectile dysfunction available in Turkey?",
      a: "Some providers advertise exosome therapy for ED. Because the evidence is very limited and there is no established protocol, the sensible step is a specialist assessment before any decision. At UZ Clinic Antalya, availability is considered only after clinical evaluation, and you can send your case first.",
    },
    ctaLabel: "Check Exosome Therapy Suitability",
    modified: DATE,
    priority: 0.75,
    schema: { therapy: "Exosome therapy (investigational)", condition: "Erectile dysfunction" },
    blocks: [
      {
        type: "text",
        heading: "Questions to ask any provider",
        id: "questions",
        bullets: [
          "What is the product, where does it come from and how is it prepared and tested?",
          "What evidence supports it for ED in men like me?",
          "Is it offered within a registered study, and what consent is given?",
          "What risks and follow-up are documented?",
          "Why is it recommended before established treatments?",
        ],
      },
      { type: "cta", title: "Ask Before You Book Any Travel", text: "Send your case. The clinic will say whether an investigational option is worth discussing.", label: "Ask Whether Exosome Therapy Is Suitable for Your Case" },
      {
        type: "callout",
        tone: "evidence",
        title: "Investigational, with very limited human evidence",
        text: "The clinic does not publish doses, success rates or outcome claims for exosome therapy. " + NO_GUARANTEE,
      },
      { type: "international" },
      { type: "doctor" },
    ],
    faqs: [
      { q: "Can the clinic confirm exosome availability before I travel?", a: "Availability is confirmed after your case is reviewed and, where needed, after an in-person assessment." },
      { q: "What if exosome therapy is not suitable for me?", a: "The doctor explains which other options may be relevant to the likely cause of your ED." },
    ],
    sources: ["eau2026"],
    related: ["/exosome-therapy-erectile-dysfunction", "/international-patients", "/erectile-dysfunction-assessment"],
  },
];

