// Short breadcrumb labels. Long H1s truncate in search results, so the trail uses these instead.
export const breadcrumbLabels: Record<string, string> = {
  "/erectile-dysfunction": "Erectile dysfunction",
  "/erectile-dysfunction-treatment": "ED treatment",
  "/ed-treatment-options": "ED treatment options",
  "/erectile-dysfunction-treatment-turkey": "ED treatment in Turkey",
  "/erectile-dysfunction-treatment-antalya": "ED treatment in Antalya",
  "/p-shot": "P-Shot",
  "/p-shot-turkey": "P-Shot in Turkey",
  "/p-shot-antalya": "P-Shot in Antalya",
  "/prp-for-erectile-dysfunction": "PRP for ED",
  "/shockwave-therapy-ed": "Shockwave therapy",
  "/edswt": "EdSWT protocol",
  "/shockwave-therapy-erectile-dysfunction-turkey": "Shockwave in Turkey",
  "/stem-cell-therapy-erectile-dysfunction": "Stem cell therapy",
  "/stem-cell-treatment-ed-turkey": "Stem cells in Turkey",
  "/exosome-therapy-erectile-dysfunction": "Exosome therapy",
  "/exosome-therapy-turkey": "Exosomes in Turkey",
  "/vasculogenic-erectile-dysfunction": "Vasculogenic ED",
  "/venous-leak": "Venous leak",
  "/erectile-dysfunction-after-prostate-surgery": "ED after prostate surgery",
  "/diabetes-erectile-dysfunction": "Diabetes and ED",
  "/erectile-dysfunction-over-50": "ED over 50",
  "/erectile-dysfunction-over-60": "ED over 60",
  "/erectile-dysfunction-assessment": "ED assessment",
  "/penile-doppler-ultrasound": "Penile Doppler",
  "/p-shot-vs-shockwave": "P-Shot vs shockwave",
  "/p-shot-vs-stem-cell": "P-Shot vs stem cell",
  "/shockwave-vs-stem-cell": "Shockwave vs stem cell",
  "/penile-rehabilitation": "Penile rehabilitation",
  "/penile-implant": "Penile implant",
  "/dr-niyazi-umut-ozdemir": "Dr. Niyazi Umut Özdemir",
  "/about": "About the clinic",
  "/international-patients": "International patients",
  "/patient-experiences": "Patient experiences",
  "/price": "P-Shot price",
  "/side-effects": "P-Shot side effects",
  "/ed-knowledge-hub": "ED knowledge hub",
  "/editorial-policy": "Editorial policy",
  "/evidence-methodology": "Evidence methodology",
  "/privacy": "Privacy",
  "/testosterone-ed": "Testosterone and ED",
  "/post-finasteride-syndrome-ed": "Finasteride and ED",
  "/p-shot-vs-viagra": "P-Shot vs Viagra",
};
